//! Build script for finetype_duckdb.
//!
//! Embeds the taxonomy YAML definitions (`labels/definitions_*.yaml`) so the
//! extension can run validation-based disambiguation at runtime without a
//! `labels/` directory on the host. Model weights and Model2Vec resources are
//! NOT embedded — they are fetched from HuggingFace (or `FINETYPE_MODEL_DIR`) at
//! first use. The taxonomy is small text and must match the binary, so it is
//! baked in rather than downloaded.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn portable_path(p: &Path) -> String {
    p.canonicalize()
        .unwrap_or_else(|e| panic!("Cannot canonicalize {}: {e}", p.display()))
        .to_string_lossy()
        .replace('\\', "/")
}

fn main() {
    // labels/ lives at the workspace root, two levels up from this crate.
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let workspace_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("crate is expected at <workspace>/crates/finetype-duckdb")
        .to_path_buf();
    let labels_dir = workspace_root.join("labels");

    println!("cargo:rerun-if-changed={}", labels_dir.display());

    let mut yaml_paths: Vec<PathBuf> = fs::read_dir(&labels_dir)
        .unwrap_or_else(|e| panic!("Failed to read labels dir {}: {e}", labels_dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| {
            p.file_name()
                .and_then(|n| n.to_str())
                .map(|n| n.starts_with("definitions_") && n.ends_with(".yaml"))
                .unwrap_or(false)
        })
        .collect();
    yaml_paths.sort();

    assert!(
        !yaml_paths.is_empty(),
        "No definitions_*.yaml found in {}",
        labels_dir.display()
    );

    let mut code = String::from("// Auto-generated by build.rs — do not edit\n\n");
    code.push_str("pub const TAXONOMY_YAMLS: &[&str] = &[\n");
    for path in &yaml_paths {
        code.push_str(&format!("    include_str!(\"{}\"),\n", portable_path(path)));
    }
    code.push_str("];\n");

    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("embedded_taxonomy.rs");
    fs::write(&dest, code).unwrap_or_else(|e| panic!("Failed to write {}: {e}", dest.display()));
}
