//! Build script for finetype_duckdb.
//!
//! When the `embed-models` feature is enabled, this script embeds the flat CharCNN
//! model weights, labels, and config at compile time via `include_bytes!`.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Convert a path to a string safe for use inside `include_bytes!()` / `include_str!()`.
/// On Windows, `canonicalize()` produces `\\?\D:\...` paths with backslashes that Rust
/// interprets as escape sequences. Forward slashes work on all platforms.
fn portable_path(p: &Path) -> String {
    p.canonicalize()
        .unwrap()
        .to_string_lossy()
        .replace('\\', "/")
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let models_base = PathBuf::from(&manifest_dir).join("../../models");

    // Rerun if models directory or default symlink changes
    println!("cargo:rerun-if-changed={}", models_base.display());
    println!(
        "cargo:rerun-if-changed={}",
        models_base.join("default").display()
    );

    #[cfg(feature = "embed-models")]
    generate_embedded_models(&models_base);

    #[cfg(not(feature = "embed-models"))]
    let _ = models_base;
}

#[cfg(feature = "embed-models")]
fn generate_embedded_models(models_base: &std::path::Path) {
    // Follow the models/default symlink to find the active model
    let default_link = models_base.join("default");
    let flat_dir = if default_link.exists() {
        std::fs::read_link(&default_link)
            .map(|target| {
                if target.is_relative() {
                    models_base.join(target)
                } else {
                    target
                }
            })
            .unwrap_or_else(|_| models_base.join("char-cnn-v2"))
    } else {
        models_base.join("char-cnn-v2")
    };

    // Verify model exists
    assert!(
        flat_dir.join("model.safetensors").exists(),
        "Model not found at {:?}. Run from workspace root or disable embed-models feature.",
        flat_dir
    );

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = PathBuf::from(&out_dir).join("embedded_models.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit\n");
    code.push_str("// Embeds model weights, labels, and configs at compile time.\n\n");

    // Embed model files (portable_path normalises Windows backslashes to forward slashes)
    let weights_path = portable_path(&flat_dir.join("model.safetensors"));
    let labels_path = portable_path(&flat_dir.join("labels.json"));
    let config_path = portable_path(&flat_dir.join("config.yaml"));

    code.push_str(&format!(
        "pub const FLAT_WEIGHTS: &[u8] = include_bytes!(\"{weights_path}\");\n"
    ));
    code.push_str(&format!(
        "pub const FLAT_LABELS: &[u8] = include_bytes!(\"{labels_path}\");\n"
    ));
    code.push_str(&format!(
        "pub const FLAT_CONFIG: &[u8] = include_bytes!(\"{config_path}\");\n"
    ));

    fs::write(&dest, code).unwrap_or_else(|e| panic!("Failed to write {}: {}", dest.display(), e));
}
