//! Validation-as-veto for the profile path.
//!
//! Validation is an ASYMMETRIC signal (memory `validation-gate-asymmetry`):
//! a low pass-rate is a reliable NO ("the predicted type is contradicted by
//! the values"), but a high pass-rate is an unreliable YES. So profile uses
//! validation only to *veto* its own prediction, never to assert one.
//!
//! The veto is HARD (NULL the predicted label) only for labels on the
//! audited-safe allowlist — types the corpus-wide false-veto sweep MEASURED
//! as non-brittle (>= 20 both-lens agreement columns, < 10% false-veto rate
//! after the ac-01/02/03 fixes). For every other label the sweep could not
//! measure (rare-type starvation), the pass-rate is surfaced as ADVISORY
//! only — flagged, never NULLed — until it becomes measurable.
//!
//! The allowlist is generated by `scripts/false_veto_sweep.py` and embedded
//! at compile time, so the runtime veto scope cannot drift from the swept
//! evidence.

use std::collections::HashSet;

use crate::taxonomy::Taxonomy;
use crate::validator::{validate_column_for_label, InvalidStrategy};

/// The canonical pass-rate veto threshold — matches `ydf_prediction_gated`
/// (a prediction is vetoed when fewer than half its sample values pass the
/// predicted type's validation).
pub const VETO_THRESHOLD: f64 = 0.5;

/// Audited-safe allowlist, generated by `scripts/false_veto_sweep.py`.
/// One label per line; `#`-prefixed lines and blanks are provenance.
const VETO_SAFE_RAW: &str = include_str!("../../../labels/veto_safe.txt");

/// Parse the embedded allowlist into a set of audited-safe labels.
pub fn audited_safe_labels() -> HashSet<String> {
    VETO_SAFE_RAW
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(str::to_string)
        .collect()
}

/// Outcome of validating a column against its predicted label.
#[derive(Debug, Clone)]
pub struct ValidationVeto {
    /// Fraction of non-null sample values passing the predicted type's
    /// validation. `None` when the label has no applicable validation (no
    /// evidence either way — never vetoed).
    pub pass_rate: Option<f64>,
    /// HARD veto: pass-rate is below threshold AND the label is on the
    /// audited-safe allowlist. The caller NULLs the predicted label.
    pub vetoed: bool,
    /// ADVISORY: pass-rate is below threshold but the label is NOT
    /// audited-safe (the sweep could not measure it). Flagged, not NULLed.
    pub advisory_low: bool,
}

impl ValidationVeto {
    /// No applicable validation — the prediction stands unflagged.
    fn inert() -> Self {
        ValidationVeto {
            pass_rate: None,
            vetoed: false,
            advisory_low: false,
        }
    }
}

/// Evaluate a predicted label against a column's sample values.
///
/// Returns an inert (no-op) veto when the label has no validation in the
/// taxonomy, or when there are no non-null values to check. Otherwise the
/// pass-rate is computed; a sub-threshold rate becomes a HARD veto when the
/// label is in `safe`, else an ADVISORY flag.
pub fn evaluate_validation_veto(
    label: &str,
    values: &[Option<&str>],
    taxonomy: &Taxonomy,
    safe: &HashSet<String>,
) -> ValidationVeto {
    let result =
        match validate_column_for_label(values, label, taxonomy, InvalidStrategy::Quarantine) {
            Ok(r) => r,
            // Unknown label or no schema — no validation signal.
            Err(_) => return ValidationVeto::inert(),
        };

    let checked = result.stats.valid_count + result.stats.invalid_count;
    if checked == 0 {
        return ValidationVeto::inert();
    }

    let pass_rate = result.stats.valid_count as f64 / checked as f64;
    let below = pass_rate < VETO_THRESHOLD;
    let is_safe = safe.contains(label);

    ValidationVeto {
        pass_rate: Some(pass_rate),
        vetoed: below && is_safe,
        advisory_low: below && !is_safe,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::taxonomy::Taxonomy;

    // Inline taxonomy: `datetime.component.year` (which the real embedded
    // allowlist marks audited-safe) plus `identity.person.gender_code`
    // (which the sweep could not measure — advisory only).
    const VETO_YAML: &str = r#"
datetime.component.year:
  title: "Year"
  description: "Four-digit calendar year"
  designation: universal
  locales: [UNIVERSAL]
  broad_type: INTEGER
  format_string: null
  transform: null
  transform_ext: null
  decompose: null
  validation:
    type: string
    pattern: "^\\d{4}(\\.0+)?$"
  tier: [INTEGER, year]
  release_priority: 5
  aliases: []
  samples: ["1998"]
  references: null
  notes: null
identity.person.gender_code:
  title: "Gender code"
  description: "Coded sex field"
  designation: universal
  locales: [UNIVERSAL]
  broad_type: STRING
  format_string: null
  transform: null
  transform_ext: null
  decompose: null
  validation:
    type: string
    enum: ["M", "F", "X", "0", "1", "2", "9"]
  tier: [STRING, gender_code]
  release_priority: 5
  aliases: []
  samples: ["M"]
  references: null
  notes: null
"#;

    fn taxonomy() -> Taxonomy {
        let mut t = Taxonomy::from_yaml(VETO_YAML).expect("parse inline taxonomy");
        t.compile_validators();
        t
    }

    #[test]
    fn allowlist_loads_and_excludes_comments() {
        let safe = audited_safe_labels();
        // Sweep-measured safe labels are present.
        assert!(safe.contains("datetime.component.year"));
        assert!(safe.contains("identity.person.gender"));
        assert!(safe.contains("datetime.component.day_of_week"));
        // Provenance lines never leak in as labels.
        assert!(!safe.iter().any(|l| l.starts_with('#')));
        assert!(!safe.contains(""));
        // gender_code was too rare to measure — advisory only, not safe.
        assert!(!safe.contains("identity.person.gender_code"));
    }

    #[test]
    fn safe_label_with_failing_values_is_hard_vetoed() {
        let safe = audited_safe_labels();
        // Single/double-digit values are not four-digit years.
        let values: Vec<Option<&str>> = vec![Some("5"), Some("9"), Some("12"), Some("88")];
        let veto = evaluate_validation_veto("datetime.component.year", &values, &taxonomy(), &safe);
        assert!(veto.pass_rate.unwrap() < VETO_THRESHOLD);
        assert!(veto.vetoed, "audited-safe + failing => hard veto");
        assert!(!veto.advisory_low);
    }

    #[test]
    fn safe_label_with_passing_values_is_not_vetoed() {
        let safe = audited_safe_labels();
        let values: Vec<Option<&str>> =
            vec![Some("1998"), Some("2001"), Some("1850"), Some("2020")];
        let veto = evaluate_validation_veto("datetime.component.year", &values, &taxonomy(), &safe);
        assert!(veto.pass_rate.unwrap() >= VETO_THRESHOLD);
        assert!(!veto.vetoed);
        assert!(!veto.advisory_low);
    }

    #[test]
    fn unmeasured_label_failing_is_advisory_not_hard() {
        // Real allowlist: gender_code is absent, so the failing values
        // produce an advisory flag, never a hard veto.
        let safe = audited_safe_labels();
        let values: Vec<Option<&str>> = vec![Some("nope"), Some("zzz")];
        let veto =
            evaluate_validation_veto("identity.person.gender_code", &values, &taxonomy(), &safe);
        assert!(veto.pass_rate.unwrap() < VETO_THRESHOLD);
        assert!(!veto.vetoed, "not audited-safe => never hard-vetoed");
        assert!(veto.advisory_low);
    }
}
