//! Validation-as-veto for the profile path.
//!
//! Validation is an ASYMMETRIC signal (memory `validation-gate-asymmetry`):
//! a low pass-rate is a reliable NO ("the predicted type is contradicted by
//! the values"), but a high pass-rate is an unreliable YES. So profile uses
//! validation only to *veto* its own prediction, never to assert one.
//!
//! The veto is HARD (NULL the predicted label) only for labels on the
//! audited-safe allowlist — types the corpus-wide false-veto sweep MEASURED
//! as non-brittle (>= 20 both-lens agreement columns, < 10% false-veto rate
//! after the ac-01/02/03 fixes). For every other label the sweep could not
//! measure (rare-type starvation), the pass-rate is surfaced as ADVISORY
//! only — flagged, never NULLed — until it becomes measurable.
//!
//! The allowlist is generated by `scripts/false_veto_sweep.py` and embedded
//! at compile time, so the runtime veto scope cannot drift from the swept
//! evidence.

use std::collections::HashSet;

use crate::taxonomy::Taxonomy;
use crate::validator::{validate_column_for_label, InvalidStrategy};

/// The canonical pass-rate veto threshold — matches `ydf_prediction_gated`
/// (a prediction is vetoed when fewer than half its sample values pass the
/// predicted type's validation).
pub const VETO_THRESHOLD: f64 = 0.5;

/// Audited-safe allowlist, generated by `scripts/false_veto_sweep.py`.
/// One label per line; `#`-prefixed lines and blanks are provenance.
const VETO_SAFE_RAW: &str = include_str!("../../../labels/veto_safe.txt");

/// Parse the embedded allowlist into a set of audited-safe labels.
pub fn audited_safe_labels() -> HashSet<String> {
    VETO_SAFE_RAW
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(str::to_string)
        .collect()
}

/// Outcome of validating a column against its predicted label.
#[derive(Debug, Clone)]
pub struct ValidationVeto {
    /// Fraction of non-null sample values passing the predicted type's
    /// validation. `None` when the label has no applicable validation (no
    /// evidence either way — never vetoed).
    pub pass_rate: Option<f64>,
    /// HARD veto: pass-rate is below threshold AND the label is on the
    /// audited-safe allowlist. The caller NULLs the predicted label.
    pub vetoed: bool,
    /// ADVISORY: pass-rate is below threshold but the label is NOT
    /// audited-safe (the sweep could not measure it). Flagged, not NULLed.
    pub advisory_low: bool,
}

impl ValidationVeto {
    /// No applicable validation — the prediction stands unflagged.
    fn inert() -> Self {
        ValidationVeto {
            pass_rate: None,
            vetoed: false,
            advisory_low: false,
        }
    }
}

/// Evaluate a predicted label against a column's sample values.
///
/// Returns an inert (no-op) veto when the label has no validation in the
/// taxonomy, or when there are no non-null values to check. Otherwise the
/// pass-rate is computed; a sub-threshold rate becomes a HARD veto when the
/// label is in `safe`, else an ADVISORY flag.
pub fn evaluate_validation_veto(
    label: &str,
    values: &[Option<&str>],
    taxonomy: &Taxonomy,
    safe: &HashSet<String>,
) -> ValidationVeto {
    let result =
        match validate_column_for_label(values, label, taxonomy, InvalidStrategy::Quarantine) {
            Ok(r) => r,
            // Unknown label or no schema — no validation signal.
            Err(_) => return ValidationVeto::inert(),
        };

    let checked = result.stats.valid_count + result.stats.invalid_count;
    if checked == 0 {
        return ValidationVeto::inert();
    }

    let pass_rate = result.stats.valid_count as f64 / checked as f64;
    let below = pass_rate < VETO_THRESHOLD;
    let is_safe = safe.contains(label);

    ValidationVeto {
        pass_rate: Some(pass_rate),
        vetoed: below && is_safe,
        advisory_low: below && !is_safe,
    }
}

/// Fallback label for a HARD-vetoed column, decided from value shape alone
/// (spec 2026-06-12-veto-shape-fallback). A veto means "the asserted tight
/// type is contradicted by the values" — but the column may still carry a
/// RESIDUAL shape the flat Sense head cannot express as a precedence:
///
/// - id-shape: mostly-distinct values that mix letters and digits →
///   `representation.identifier.alphanumeric_id`
/// - vocab-shape: a small vocabulary repeated across the column →
///   `representation.discrete.categorical`
///
/// Returns `None` (the column stays `unknown`) for everything else —
/// free text, pure-numeric ids, constant columns, columns too short to
/// judge. Callers must not apply a fallback equal to the vetoed label.
///
/// Why a rule and not training data: categorical trained as a flat-softmax
/// shape class is a presence-driven attractor (memory
/// `categorical-is-a-residual-category`; v23 +529%, v27 proxy 5.76×/6.22×).
pub fn veto_shape_fallback(values: &[Option<&str>]) -> Option<&'static str> {
    let non_null: Vec<&str> = values
        .iter()
        .filter_map(|v| *v)
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .collect();
    let n = non_null.len();
    if n < 3 {
        return None;
    }

    // epoch-shape (BACKLOG #5): a pure-integer column in the narrow Unix-epoch
    // band. When an identifier header-hint (npi / numeric_code) is asserted on
    // epoch integers the validator hard-vetoes them; recover to the datetime leaf
    // instead of declining to `unknown`. Post-hard-veto (this fn IS the fallback)
    // + decline-only. Must precede the id-shape block, whose `distinct_ratio >=
    // 0.7` arm returns None for pure-numeric columns. Bands are deliberately tight
    // ([1e9,2e9] / [1e12,2e12]); ALL values must parse as ints AND sit in one band,
    // so ordinary large integers (counts, 10-digit IDs past 2e9, phone numbers)
    // fall outside.
    const EPOCH_SEC_MIN: i64 = 1_000_000_000; // 2001-09-09
    const EPOCH_SEC_MAX: i64 = 2_000_000_000; // 2033-05-18
    const EPOCH_MS_MIN: i64 = 1_000_000_000_000; // 2001-09-09
    const EPOCH_MS_MAX: i64 = 2_000_000_000_000; // 2033-05-18
    let parse_int = |v: &str| -> Option<i64> {
        v.parse::<i64>().ok().or_else(|| {
            v.parse::<f64>()
                .ok()
                .filter(|f| f.fract() == 0.0)
                .map(|f| f as i64)
        })
    };
    let ints: Vec<i64> = non_null.iter().filter_map(|v| parse_int(v)).collect();
    if ints.len() == n {
        if ints
            .iter()
            .all(|x| (EPOCH_SEC_MIN..=EPOCH_SEC_MAX).contains(x))
        {
            return Some("datetime.epoch.unix_seconds");
        }
        if ints
            .iter()
            .all(|x| (EPOCH_MS_MIN..=EPOCH_MS_MAX).contains(x))
        {
            return Some("datetime.epoch.unix_milliseconds");
        }
    }

    let distinct: HashSet<&str> = non_null.iter().copied().collect();
    let distinct_ratio = distinct.len() as f64 / n as f64;

    // id-shape: mostly distinct AND most values mix letters with digits.
    if distinct_ratio >= 0.7 {
        let mixed = non_null
            .iter()
            .filter(|v| {
                v.chars().any(|c| c.is_ascii_alphabetic()) && v.chars().any(|c| c.is_ascii_digit())
            })
            .count();
        if mixed as f64 / n as f64 >= 0.6 {
            return Some("representation.identifier.alphanumeric_id");
        }
        // digit-separator id (BACKLOG #13/#18): letter-free values that are
        // digit groups joined by a separator (`-`, `_`, `/`) are composite
        // identifiers (IPNI `69732-1`, tax id `0480196-01-999`, genomic coord
        // `15_77227420`), not numbers — `alphanumeric_id`'s validation pattern
        // hard-vetoes them because it requires a letter. Require near-unique
        // values (genuine ids) and screen out calendar dates / short ranges.
        if distinct_ratio >= 0.9 && non_null.iter().all(|v| is_digit_separator_id(v)) {
            return Some("representation.identifier.alphanumeric_id");
        }
        // numeric residual (BACKLOG #4, idx 74/103/104): letter-free, mostly-distinct
        // values that are all plain numbers are integers/decimals, not unknown. Post-
        // hard-veto only (this fn IS the veto fallback), so it cannot relocate a
        // non-vetoed column. Leading-zero guard: a multi-digit integer part starting
        // with '0' ("007", "00123") is a zero-padded CODE, not an integer — bail to
        // unknown rather than strip the semantically load-bearing padding.
        if non_null.iter().all(|v| is_plain_number(v)) {
            let zero_padded = non_null.iter().any(|v| {
                let int_part = v
                    .trim_start_matches(['+', '-'])
                    .split('.')
                    .next()
                    .unwrap_or("");
                int_part.len() > 1 && int_part.starts_with('0')
            });
            if !zero_padded {
                return Some(if non_null.iter().any(|v| v.contains('.')) {
                    "representation.numeric.decimal_number"
                } else {
                    "representation.numeric.integer_number"
                });
            }
        }
        return None;
    }

    // vocab-shape: a small vocabulary, genuinely repeated. `categorical` is retired
    // as an emitted label (choice 0102) — a bounded vocabulary with no semantic type
    // is the honest text residual `word`; its bounded-ness is surfaced separately as
    // the x-finetype-enum property.
    if n >= 4 && (2..=12).contains(&distinct.len()) && distinct_ratio <= 0.6 {
        return Some("representation.text.word");
    }

    None
}

/// A digit-separator identifier: two or more all-digit groups joined by `-` or
/// `_`, with at least 6 digits total, that is NOT a date or time. Recovers
/// composite numeric ids (`69732-1`, `0480196-01-999`, `15_77227420`,
/// `156794164312_10154286`) that `alphanumeric_id`'s letter-requiring validation
/// pattern hard-vetoes (BACKLOG #13/#18 helper).
///
/// `/` is deliberately NOT a separator: slash-joined digit runs are fractions
/// (`1397/2400`) and slash dates (`3/10/2010`), never composite ids. The
/// temporal screen rejects a value whose EVERY group is a valid calendar/clock
/// component — a small day/month (`12`), a 4-digit year, a packed `YYYYMMDD`,
/// or a packed `HHMMSS` — which covers `2021-03-15`, `2020-10-20_12-25-49` and
/// `20190619-140629`. A genuine id carries at least one group that none of
/// those shapes admit (`69732`, `77227420`, `156794164312`).
fn is_digit_separator_id(v: &str) -> bool {
    let groups: Vec<&str> = v.split(['-', '_']).collect();
    if groups.len() < 2 {
        return false;
    }
    if !groups
        .iter()
        .all(|g| !g.is_empty() && g.bytes().all(|b| b.is_ascii_digit()))
    {
        return false;
    }
    let total_digits: usize = groups.iter().map(|g| g.len()).sum();
    if total_digits < 6 {
        return false;
    }
    // An id needs at least one group that is not a plausible date/time component.
    groups.iter().any(|g| !is_temporal_component(g))
}

/// Whether a pure-digit group could be a single calendar/clock component:
/// a 1–2 digit day/month/hour/minute/second, a 4-digit year, a packed
/// `HHMMSS`, or a packed `YYYYMMDD`. Packed forms are bounds-checked so a long
/// id digit-run (`77227420` → month 74) is not mistaken for one.
fn is_temporal_component(g: &str) -> bool {
    let n = |a: usize, b: usize| g[a..b].parse::<u32>().unwrap_or(u32::MAX);
    match g.len() {
        1 | 2 => true,
        4 => g.parse::<u32>().is_ok_and(|y| (1900..=2100).contains(&y)),
        6 => n(0, 2) <= 23 && n(2, 4) <= 59 && n(4, 6) <= 59, // HHMMSS
        8 => {
            (1900..=2100).contains(&n(0, 4))
                && (1..=12).contains(&n(4, 6))
                && (1..=31).contains(&n(6, 8))
        } // YYYYMMDD
        _ => false,
    }
}

/// A plain base-10 number: an optional sign then digits with at most one '.'.
/// Deliberately excludes scientific notation / NaN / inf so f64::parse edge
/// cases cannot masquerade as numeric residuals (BACKLOG #4 helper).
fn is_plain_number(v: &str) -> bool {
    let body = v.strip_prefix(['+', '-']).unwrap_or(v);
    !body.is_empty()
        && body.chars().all(|c| c.is_ascii_digit() || c == '.')
        && body.chars().filter(|c| *c == '.').count() <= 1
        && body.chars().any(|c| c.is_ascii_digit())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::taxonomy::Taxonomy;

    // Inline taxonomy: `datetime.component.year` (which the real embedded
    // allowlist marks audited-safe) plus `identity.person.gender_code`
    // (which the sweep could not measure — advisory only).
    const VETO_YAML: &str = r#"
datetime.component.year:
  title: "Year"
  description: "Four-digit calendar year"
  designation: universal
  locales: [UNIVERSAL]
  broad_type: INTEGER
  format_string: null
  transform: null
  transform_ext: null
  decompose: null
  validation:
    type: string
    pattern: "^\\d{4}(\\.0+)?$"
  tier: [INTEGER, year]
  release_priority: 5
  aliases: []
  samples: ["1998"]
  references: null
  notes: null
identity.person.gender_code:
  title: "Gender code"
  description: "Coded sex field"
  designation: universal
  locales: [UNIVERSAL]
  broad_type: STRING
  format_string: null
  transform: null
  transform_ext: null
  decompose: null
  validation:
    type: string
    enum: ["M", "F", "X", "0", "1", "2", "9"]
  tier: [STRING, gender_code]
  release_priority: 5
  aliases: []
  samples: ["M"]
  references: null
  notes: null
"#;

    fn taxonomy() -> Taxonomy {
        let mut t = Taxonomy::from_yaml(VETO_YAML).expect("parse inline taxonomy");
        t.compile_validators();
        t
    }

    #[test]
    fn allowlist_loads_and_excludes_comments() {
        let safe = audited_safe_labels();
        // Sweep-measured safe labels are present.
        assert!(safe.contains("datetime.component.year"));
        assert!(safe.contains("identity.person.gender"));
        assert!(safe.contains("datetime.component.day_of_week"));
        // Provenance lines never leak in as labels.
        assert!(!safe.iter().any(|l| l.starts_with('#')));
        assert!(!safe.contains(""));
        // gender_code was too rare to measure — advisory only, not safe.
        assert!(!safe.contains("identity.person.gender_code"));
    }

    #[test]
    fn safe_label_with_failing_values_is_hard_vetoed() {
        let safe = audited_safe_labels();
        // Single/double-digit values are not four-digit years.
        let values: Vec<Option<&str>> = vec![Some("5"), Some("9"), Some("12"), Some("88")];
        let veto = evaluate_validation_veto("datetime.component.year", &values, &taxonomy(), &safe);
        assert!(veto.pass_rate.unwrap() < VETO_THRESHOLD);
        assert!(veto.vetoed, "audited-safe + failing => hard veto");
        assert!(!veto.advisory_low);
    }

    #[test]
    fn safe_label_with_passing_values_is_not_vetoed() {
        let safe = audited_safe_labels();
        let values: Vec<Option<&str>> =
            vec![Some("1998"), Some("2001"), Some("1850"), Some("2020")];
        let veto = evaluate_validation_veto("datetime.component.year", &values, &taxonomy(), &safe);
        assert!(veto.pass_rate.unwrap() >= VETO_THRESHOLD);
        assert!(!veto.vetoed);
        assert!(!veto.advisory_low);
    }

    #[test]
    fn unmeasured_label_failing_is_advisory_not_hard() {
        // Real allowlist: gender_code is absent, so the failing values
        // produce an advisory flag, never a hard veto.
        let safe = audited_safe_labels();
        let values: Vec<Option<&str>> = vec![Some("nope"), Some("zzz")];
        let veto =
            evaluate_validation_veto("identity.person.gender_code", &values, &taxonomy(), &safe);
        assert!(veto.pass_rate.unwrap() < VETO_THRESHOLD);
        assert!(!veto.vetoed, "not audited-safe => never hard-vetoed");
        assert!(veto.advisory_low);
    }

    // === veto_shape_fallback (spec 2026-06-12-veto-shape-fallback) ===

    fn opts(vals: &[&'static str]) -> Vec<Option<&'static str>> {
        vals.iter().map(|v| Some(*v)).collect()
    }

    #[test]
    fn fallback_id_shape_on_generic_ids() {
        // The gold mechanism: msg/wfo-style ids asserted as h3/hash, vetoed.
        let msg = opts(&["msg24159928", "msg24161498", "msg24168398", "msg24173983"]);
        assert_eq!(
            veto_shape_fallback(&msg),
            Some("representation.identifier.alphanumeric_id")
        );
        let wfo = opts(&["wfo-4000021847", "wfo-0001278270", "wfo-0000891258"]);
        assert_eq!(
            veto_shape_fallback(&wfo),
            Some("representation.identifier.alphanumeric_id")
        );
    }

    #[test]
    fn fallback_digit_separator_ids() {
        // BACKLOG #13/#18: letter-free digit groups joined by a separator are
        // composite ids, not numbers — recover to alphanumeric_id.
        let ipni = opts(&["69732-1", "442514-1", "774083-1", "131795-2"]);
        assert_eq!(
            veto_shape_fallback(&ipni),
            Some("representation.identifier.alphanumeric_id")
        );
        let ttx = opts(&["0480196-01-999", "1172642-12-171", "1347285-11-231"]);
        assert_eq!(
            veto_shape_fallback(&ttx),
            Some("representation.identifier.alphanumeric_id")
        );
        let coord = opts(&["15_77227420", "2_32884931", "21_25412449", "8_29807728"]);
        assert_eq!(
            veto_shape_fallback(&coord),
            Some("representation.identifier.alphanumeric_id")
        );
    }

    #[test]
    fn fallback_digit_separator_rejects_false_friends() {
        // Year-month dates are not ids.
        let ym = opts(&["2021-03", "2021-04", "2020-11", "2019-07"]);
        assert_eq!(veto_shape_fallback(&ym), None);
        // Full ISO dates are not ids.
        let ymd = opts(&["2021-03-15", "2021-04-02", "2020-11-30", "2019-07-21"]);
        assert_eq!(veto_shape_fallback(&ymd), None);
        // M/D/YYYY slash dates (year LAST) are not ids — `/` is not a separator
        // AND every group is a plausible day/month/year (the `DOB` false friend).
        let mdy = opts(&["3/10/2010", "5/1/2013", "2/3/2011", "6/18/2011"]);
        assert_eq!(veto_shape_fallback(&mdy), None);
        // Packed date_time strings are not ids (the `date`/`Time` false friends).
        let dt = opts(&[
            "2020-10-20_12-25-49",
            "2020-10-20_12-26-50",
            "2020-01-09_17-46-25",
            "2020-01-09_17-47-43",
        ]);
        assert_eq!(veto_shape_fallback(&dt), None);
        let packed = opts(&["20190619-140629", "20190619-140637", "20190619-140605"]);
        assert_eq!(veto_shape_fallback(&packed), None);
        // Slash fractions are not ids (the `Total` false friend).
        let frac = opts(&["1397/2400", "1526/2300", "1158/2300", "1334/2300"]);
        assert_eq!(veto_shape_fallback(&frac), None);
        // Year ranges are not ids.
        let yr = opts(&["1999-2024", "2001-2020", "1990-2010", "2005-2022"]);
        assert_eq!(veto_shape_fallback(&yr), None);
        // Short ranges (under the 6-digit floor) are not ids.
        let ranges = opts(&["10-20", "30-40", "50-60", "70-80"]);
        assert_eq!(veto_shape_fallback(&ranges), None);
    }

    #[test]
    fn fallback_vocab_shape_on_small_repeating_vocabulary() {
        let vocab = opts(&["comment", "story", "comment", "comment", "story", "comment"]);
        // Enum reframe (0102): small bounded vocab -> text residual `word`, not categorical.
        assert_eq!(
            veto_shape_fallback(&vocab),
            Some("representation.text.word")
        );
    }

    #[test]
    fn fallback_none_on_free_text() {
        // Mostly distinct but no letter+digit mix — not an id, not a vocab.
        let text = opts(&["alpha", "bravo", "charlie", "delta", "echo"]);
        assert_eq!(veto_shape_fallback(&text), None);
    }

    #[test]
    fn fallback_none_on_zero_padded_codes() {
        // Zero-padded codes are NOT integers — the padding is load-bearing, so the
        // numeric-residual arm (BACKLOG #4) bails to unknown rather than strip it.
        let padded = opts(&["00123", "00456", "00789", "00321"]);
        assert_eq!(veto_shape_fallback(&padded), None);
    }

    #[test]
    fn fallback_numeric_residual_beats_unknown() {
        // BACKLOG #4: post-veto, letter-free distinct numbers are integers/decimals,
        // not unknown.
        let ints = opts(&["10234", "10235", "10240", "10299"]);
        assert_eq!(
            veto_shape_fallback(&ints),
            Some("representation.numeric.integer_number")
        );
        let floats = opts(&["10.5", "10.6", "10.7", "10.8"]);
        assert_eq!(
            veto_shape_fallback(&floats),
            Some("representation.numeric.decimal_number")
        );
    }

    #[test]
    fn fallback_epoch_recovery_on_narrow_band() {
        // BACKLOG #5: post-veto pure-integer columns inside the Unix-epoch bands
        // recover to the datetime leaf, not unknown.
        let secs = opts(&["1577836800", "1609459200", "1640995200", "1672531200"]);
        assert_eq!(
            veto_shape_fallback(&secs),
            Some("datetime.epoch.unix_seconds")
        );
        let ms = opts(&[
            "1577836800000",
            "1609459200000",
            "1640995200000",
            "1672531200000",
        ]);
        assert_eq!(
            veto_shape_fallback(&ms),
            Some("datetime.epoch.unix_milliseconds")
        );
        // Out-of-band large integers spanning past 2e9 are NOT epochs → integer.
        let ids = opts(&["3000000001", "5500000002", "9990000003", "1234567890"]);
        assert_eq!(
            veto_shape_fallback(&ids),
            Some("representation.numeric.integer_number")
        );
    }

    #[test]
    fn fallback_none_on_constant_and_short_columns() {
        let constant = opts(&["s", "s", "s", "s", "s"]);
        assert_eq!(veto_shape_fallback(&constant), None, "1 distinct value");
        let short = opts(&["ab1", "cd2"]);
        assert_eq!(veto_shape_fallback(&short), None, "below n>=3 floor");
        let empties: Vec<Option<&str>> = vec![Some("  "), None, Some("")];
        assert_eq!(veto_shape_fallback(&empties), None);
    }

    #[test]
    fn fallback_none_on_wide_vocabularies() {
        // 13 distinct repeating values — beyond the <=12 vocab ceiling.
        let mut vals: Vec<&'static str> = vec![
            "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
        ];
        vals.extend_from_slice(&["a", "b", "c", "d", "e", "f", "g"]);
        assert_eq!(veto_shape_fallback(&opts(&vals)), None);
    }
}
