//! Validation-as-veto for the profile path.
//!
//! Validation is an ASYMMETRIC signal (memory `validation-gate-asymmetry`):
//! a low pass-rate is a reliable NO ("the predicted type is contradicted by
//! the values"), but a high pass-rate is an unreliable YES. So profile uses
//! validation only to *veto* its own prediction, never to assert one.
//!
//! The veto is HARD (NULL the predicted label) only for labels on the
//! audited-safe allowlist — types the corpus-wide false-veto sweep MEASURED
//! as non-brittle (>= 20 both-lens agreement columns, < 10% false-veto rate
//! after the ac-01/02/03 fixes). For every other label the sweep could not
//! measure (rare-type starvation), the pass-rate is surfaced as ADVISORY
//! only — flagged, never NULLed — until it becomes measurable.
//!
//! The allowlist is generated by `scripts/false_veto_sweep.py` and embedded
//! at compile time, so the runtime veto scope cannot drift from the swept
//! evidence.

use std::collections::HashSet;

use crate::taxonomy::Taxonomy;
use crate::validator::{validate_column_for_label, InvalidStrategy};

/// The canonical pass-rate veto threshold — matches `ydf_prediction_gated`
/// (a prediction is vetoed when fewer than half its sample values pass the
/// predicted type's validation).
pub const VETO_THRESHOLD: f64 = 0.5;

/// Audited-safe allowlist, generated by `scripts/false_veto_sweep.py`.
/// One label per line; `#`-prefixed lines and blanks are provenance.
const VETO_SAFE_RAW: &str = include_str!("../../../labels/veto_safe.txt");

/// Parse the embedded allowlist into a set of audited-safe labels.
pub fn audited_safe_labels() -> HashSet<String> {
    VETO_SAFE_RAW
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(str::to_string)
        .collect()
}

/// Outcome of validating a column against its predicted label.
#[derive(Debug, Clone)]
pub struct ValidationVeto {
    /// Fraction of non-null sample values passing the predicted type's
    /// validation. `None` when the label has no applicable validation (no
    /// evidence either way — never vetoed).
    pub pass_rate: Option<f64>,
    /// HARD veto: pass-rate is below threshold AND the label is on the
    /// audited-safe allowlist. The caller NULLs the predicted label.
    pub vetoed: bool,
    /// ADVISORY: pass-rate is below threshold but the label is NOT
    /// audited-safe (the sweep could not measure it). Flagged, not NULLed.
    pub advisory_low: bool,
}

impl ValidationVeto {
    /// No applicable validation — the prediction stands unflagged.
    fn inert() -> Self {
        ValidationVeto {
            pass_rate: None,
            vetoed: false,
            advisory_low: false,
        }
    }
}

/// Evaluate a predicted label against a column's sample values.
///
/// Returns an inert (no-op) veto when the label has no validation in the
/// taxonomy, or when there are no non-null values to check. Otherwise the
/// pass-rate is computed; a sub-threshold rate becomes a HARD veto when the
/// label is in `safe`, else an ADVISORY flag.
pub fn evaluate_validation_veto(
    label: &str,
    values: &[Option<&str>],
    taxonomy: &Taxonomy,
    safe: &HashSet<String>,
) -> ValidationVeto {
    let result =
        match validate_column_for_label(values, label, taxonomy, InvalidStrategy::Quarantine) {
            Ok(r) => r,
            // Unknown label or no schema — no validation signal.
            Err(_) => return ValidationVeto::inert(),
        };

    let checked = result.stats.valid_count + result.stats.invalid_count;
    if checked == 0 {
        return ValidationVeto::inert();
    }

    let pass_rate = result.stats.valid_count as f64 / checked as f64;
    let below = pass_rate < VETO_THRESHOLD;
    let is_safe = safe.contains(label);

    ValidationVeto {
        pass_rate: Some(pass_rate),
        vetoed: below && is_safe,
        advisory_low: below && !is_safe,
    }
}

/// Fallback label for a HARD-vetoed column, decided from value shape alone
/// (spec 2026-06-12-veto-shape-fallback). A veto means "the asserted tight
/// type is contradicted by the values" — but the column may still carry a
/// RESIDUAL shape the flat Sense head cannot express as a precedence:
///
/// - id-shape: mostly-distinct values that mix letters and digits →
///   `representation.identifier.alphanumeric_id`
/// - vocab-shape: a small vocabulary repeated across the column →
///   `representation.discrete.categorical`
///
/// Returns `None` (the column stays `unknown`) for everything else —
/// free text, pure-numeric ids, constant columns, columns too short to
/// judge. Callers must not apply a fallback equal to the vetoed label.
///
/// Why a rule and not training data: categorical trained as a flat-softmax
/// shape class is a presence-driven attractor (memory
/// `categorical-is-a-residual-category`; v23 +529%, v27 proxy 5.76×/6.22×).
pub fn veto_shape_fallback(values: &[Option<&str>]) -> Option<&'static str> {
    let non_null: Vec<&str> = values
        .iter()
        .filter_map(|v| *v)
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .collect();
    let n = non_null.len();
    if n < 3 {
        return None;
    }

    let distinct: HashSet<&str> = non_null.iter().copied().collect();
    let distinct_ratio = distinct.len() as f64 / n as f64;

    // id-shape: mostly distinct AND most values mix letters with digits.
    if distinct_ratio >= 0.7 {
        let mixed = non_null
            .iter()
            .filter(|v| {
                v.chars().any(|c| c.is_ascii_alphabetic())
                    && v.chars().any(|c| c.is_ascii_digit())
            })
            .count();
        if mixed as f64 / n as f64 >= 0.6 {
            return Some("representation.identifier.alphanumeric_id");
        }
        return None;
    }

    // vocab-shape: a small vocabulary, genuinely repeated.
    if n >= 4 && (2..=12).contains(&distinct.len()) && distinct_ratio <= 0.6 {
        return Some("representation.discrete.categorical");
    }

    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::taxonomy::Taxonomy;

    // Inline taxonomy: `datetime.component.year` (which the real embedded
    // allowlist marks audited-safe) plus `identity.person.gender_code`
    // (which the sweep could not measure — advisory only).
    const VETO_YAML: &str = r#"
datetime.component.year:
  title: "Year"
  description: "Four-digit calendar year"
  designation: universal
  locales: [UNIVERSAL]
  broad_type: INTEGER
  format_string: null
  transform: null
  transform_ext: null
  decompose: null
  validation:
    type: string
    pattern: "^\\d{4}(\\.0+)?$"
  tier: [INTEGER, year]
  release_priority: 5
  aliases: []
  samples: ["1998"]
  references: null
  notes: null
identity.person.gender_code:
  title: "Gender code"
  description: "Coded sex field"
  designation: universal
  locales: [UNIVERSAL]
  broad_type: STRING
  format_string: null
  transform: null
  transform_ext: null
  decompose: null
  validation:
    type: string
    enum: ["M", "F", "X", "0", "1", "2", "9"]
  tier: [STRING, gender_code]
  release_priority: 5
  aliases: []
  samples: ["M"]
  references: null
  notes: null
"#;

    fn taxonomy() -> Taxonomy {
        let mut t = Taxonomy::from_yaml(VETO_YAML).expect("parse inline taxonomy");
        t.compile_validators();
        t
    }

    #[test]
    fn allowlist_loads_and_excludes_comments() {
        let safe = audited_safe_labels();
        // Sweep-measured safe labels are present.
        assert!(safe.contains("datetime.component.year"));
        assert!(safe.contains("identity.person.gender"));
        assert!(safe.contains("datetime.component.day_of_week"));
        // Provenance lines never leak in as labels.
        assert!(!safe.iter().any(|l| l.starts_with('#')));
        assert!(!safe.contains(""));
        // gender_code was too rare to measure — advisory only, not safe.
        assert!(!safe.contains("identity.person.gender_code"));
    }

    #[test]
    fn safe_label_with_failing_values_is_hard_vetoed() {
        let safe = audited_safe_labels();
        // Single/double-digit values are not four-digit years.
        let values: Vec<Option<&str>> = vec![Some("5"), Some("9"), Some("12"), Some("88")];
        let veto = evaluate_validation_veto("datetime.component.year", &values, &taxonomy(), &safe);
        assert!(veto.pass_rate.unwrap() < VETO_THRESHOLD);
        assert!(veto.vetoed, "audited-safe + failing => hard veto");
        assert!(!veto.advisory_low);
    }

    #[test]
    fn safe_label_with_passing_values_is_not_vetoed() {
        let safe = audited_safe_labels();
        let values: Vec<Option<&str>> =
            vec![Some("1998"), Some("2001"), Some("1850"), Some("2020")];
        let veto = evaluate_validation_veto("datetime.component.year", &values, &taxonomy(), &safe);
        assert!(veto.pass_rate.unwrap() >= VETO_THRESHOLD);
        assert!(!veto.vetoed);
        assert!(!veto.advisory_low);
    }

    #[test]
    fn unmeasured_label_failing_is_advisory_not_hard() {
        // Real allowlist: gender_code is absent, so the failing values
        // produce an advisory flag, never a hard veto.
        let safe = audited_safe_labels();
        let values: Vec<Option<&str>> = vec![Some("nope"), Some("zzz")];
        let veto =
            evaluate_validation_veto("identity.person.gender_code", &values, &taxonomy(), &safe);
        assert!(veto.pass_rate.unwrap() < VETO_THRESHOLD);
        assert!(!veto.vetoed, "not audited-safe => never hard-vetoed");
        assert!(veto.advisory_low);
    }

    // === veto_shape_fallback (spec 2026-06-12-veto-shape-fallback) ===

    fn opts(vals: &[&'static str]) -> Vec<Option<&'static str>> {
        vals.iter().map(|v| Some(*v)).collect()
    }

    #[test]
    fn fallback_id_shape_on_generic_ids() {
        // The gold mechanism: msg/wfo-style ids asserted as h3/hash, vetoed.
        let msg = opts(&["msg24159928", "msg24161498", "msg24168398", "msg24173983"]);
        assert_eq!(
            veto_shape_fallback(&msg),
            Some("representation.identifier.alphanumeric_id")
        );
        let wfo = opts(&["wfo-4000021847", "wfo-0001278270", "wfo-0000891258"]);
        assert_eq!(
            veto_shape_fallback(&wfo),
            Some("representation.identifier.alphanumeric_id")
        );
    }

    #[test]
    fn fallback_vocab_shape_on_small_repeating_vocabulary() {
        let vocab = opts(&[
            "comment", "story", "comment", "comment", "story", "comment",
        ]);
        assert_eq!(
            veto_shape_fallback(&vocab),
            Some("representation.discrete.categorical")
        );
    }

    #[test]
    fn fallback_none_on_free_text() {
        // Mostly distinct but no letter+digit mix — not an id, not a vocab.
        let text = opts(&["alpha", "bravo", "charlie", "delta", "echo"]);
        assert_eq!(veto_shape_fallback(&text), None);
    }

    #[test]
    fn fallback_none_on_pure_numeric_ids() {
        // Distinct numerics carry no letter — numeric territory, not alnum.
        let nums = opts(&["10234", "10235", "10240", "10299"]);
        assert_eq!(veto_shape_fallback(&nums), None);
    }

    #[test]
    fn fallback_none_on_constant_and_short_columns() {
        let constant = opts(&["s", "s", "s", "s", "s"]);
        assert_eq!(veto_shape_fallback(&constant), None, "1 distinct value");
        let short = opts(&["ab1", "cd2"]);
        assert_eq!(veto_shape_fallback(&short), None, "below n>=3 floor");
        let empties: Vec<Option<&str>> = vec![Some("  "), None, Some("")];
        assert_eq!(veto_shape_fallback(&empties), None);
    }

    #[test]
    fn fallback_none_on_wide_vocabularies() {
        // 13 distinct repeating values — beyond the <=12 vocab ceiling.
        let mut vals: Vec<&'static str> = vec![
            "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
        ];
        vals.extend_from_slice(&["a", "b", "c", "d", "e", "f", "g"]);
        assert_eq!(veto_shape_fallback(&opts(&vals)), None);
    }
}
