//! Build script for finetype CLI.
//!
//! When the `embed-models` feature is enabled, embeds the active model
//! (flat CharCNN or tiered) and taxonomy YAML files at compile time so the
//! binary works standalone. Detects tiered models by the presence of
//! tier_graph.json in the default model directory.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Convert a path to a string safe for use inside `include_bytes!()` / `include_str!()`.
/// On Windows, `canonicalize()` produces `\\?\D:\...` paths with backslashes that Rust
/// interprets as escape sequences. Forward slashes work on all platforms.
fn portable_path(p: &Path) -> String {
    p.canonicalize()
        .unwrap()
        .to_string_lossy()
        .replace('\\', "/")
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let workspace_root = PathBuf::from(&manifest_dir)
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf();

    // Models live at workspace root: models/default -> tiered-v2/ or char-cnn-v7/
    let models_base = workspace_root.join("models");
    let labels_base = workspace_root.join("labels");

    println!("cargo:rerun-if-changed={}", models_base.display());
    println!("cargo:rerun-if-changed={}", labels_base.display());

    #[cfg(feature = "embed-models")]
    generate_embedded_models(&models_base, &labels_base);

    #[cfg(not(feature = "embed-models"))]
    {
        let _ = models_base;
        let _ = labels_base;
    }
}

#[cfg(feature = "embed-models")]
fn generate_embedded_models(models_base: &std::path::Path, labels_base: &std::path::Path) {
    // Follow the models/default symlink to find the active model.
    //
    // Resolution order (handles all platforms):
    //  1. read_link — works on Linux/macOS and Windows with real symlinks
    //  2. read_to_string — Windows fallback where git checks out symlinks as
    //     plain text files containing the target path
    //
    // We skip the exists() check because on Windows a file-type symlink
    // pointing to a directory returns false for exists() even when the
    // target directory is present.
    let default_link = models_base.join("default");
    let model_dir = std::fs::read_link(&default_link)
        .map(|target| {
            if target.is_relative() {
                models_base.join(target)
            } else {
                target
            }
        })
        .or_else(|_| {
            // Windows fallback: read as plain text file (git symlink compat)
            std::fs::read_to_string(&default_link).map(|content| models_base.join(content.trim()))
        })
        .unwrap_or_else(|e| {
            panic!(
                "Cannot resolve models/default at {:?}: {e}. \
                 Run download-model.sh or create a symlink to the active model directory.",
                default_link
            )
        });

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = PathBuf::from(&out_dir).join("embedded_models.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit\n\n");

    // Detect model type: tiered (has tier_graph.json) or flat (has model.safetensors)
    let is_tiered = model_dir.join("tier_graph.json").exists();

    if is_tiered {
        generate_tiered_embeds(&model_dir, &mut code);
        // Generate empty flat stubs so main.rs compiles regardless of model type
        code.push_str("\npub const FLAT_WEIGHTS: &[u8] = &[];\n");
        code.push_str("pub const FLAT_LABELS: &[u8] = &[];\n");
        code.push_str("pub const FLAT_CONFIG: &[u8] = &[];\n");
        code.push_str("\npub const EMBEDDED_MODEL_TYPE: &str = \"tiered\";\n");
    } else {
        generate_flat_embeds(&model_dir, &mut code);
        // Generate empty tiered stubs
        code.push_str("\npub const TIER_GRAPH: &[u8] = &[];\n");
        code.push_str("pub fn get_tiered_model_data(_: &str) -> Option<(&'static [u8], &'static [u8], &'static [u8])> { None }\n");
        code.push_str("\npub const EMBEDDED_MODEL_TYPE: &str = \"flat\";\n");
    }

    // Embed taxonomy YAML files
    let mut yaml_paths: Vec<_> = fs::read_dir(labels_base)
        .expect("Failed to read labels directory")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| {
            p.file_name()
                .and_then(|n| n.to_str())
                .map(|n| n.starts_with("definitions_") && n.ends_with(".yaml"))
                .unwrap_or(false)
        })
        .collect();
    yaml_paths.sort();

    code.push_str("\npub const TAXONOMY_YAMLS: &[&str] = &[\n");
    for path in &yaml_paths {
        let canonical = portable_path(path);
        code.push_str(&format!("    include_str!(\"{canonical}\"),\n"));
    }
    code.push_str("];\n");

    // ── Model2Vec semantic hint classifier ──────────────────────────────────
    // Embeds the Model2Vec artifacts (tokenizer, embeddings, type embeddings,
    // label index) for semantic column name classification. Optional — the
    // classifier falls back to the hardcoded header_hint() when unavailable.
    let model2vec_dir = models_base.join("model2vec");
    println!("cargo:rerun-if-changed={}", model2vec_dir.display());

    if model2vec_dir.join("model.safetensors").exists() {
        let tok_path = portable_path(&model2vec_dir.join("tokenizer.json"));
        let emb_path = portable_path(&model2vec_dir.join("model.safetensors"));
        let type_path = portable_path(&model2vec_dir.join("type_embeddings.safetensors"));
        let label_path = portable_path(&model2vec_dir.join("label_index.json"));

        code.push_str("\n// Model2Vec semantic hint classifier\n");
        code.push_str("pub const HAS_MODEL2VEC: bool = true;\n");
        code.push_str(&format!(
            "pub const M2V_TOKENIZER: &[u8] = include_bytes!(\"{tok_path}\");\n"
        ));
        code.push_str(&format!(
            "pub const M2V_MODEL: &[u8] = include_bytes!(\"{emb_path}\");\n"
        ));
        code.push_str(&format!(
            "pub const M2V_TYPE_EMBEDDINGS: &[u8] = include_bytes!(\"{type_path}\");\n"
        ));
        code.push_str(&format!(
            "pub const M2V_LABEL_INDEX: &[u8] = include_bytes!(\"{label_path}\");\n"
        ));

        println!(
            "cargo:warning=Embedding Model2Vec from {}",
            model2vec_dir.display()
        );
    } else {
        code.push_str("\n// Model2Vec not available — semantic hint classifier disabled\n");
        code.push_str("pub const HAS_MODEL2VEC: bool = false;\n");
        code.push_str("pub const M2V_TOKENIZER: &[u8] = &[];\n");
        code.push_str("pub const M2V_MODEL: &[u8] = &[];\n");
        code.push_str("pub const M2V_TYPE_EMBEDDINGS: &[u8] = &[];\n");
        code.push_str("pub const M2V_LABEL_INDEX: &[u8] = &[];\n");
    }

    // ── Entity classifier (full_name demotion gate) ────────────────────────
    // Embeds the entity classifier MLP weights and config for the binary
    // demotion gate. Optional — full_name demotion is disabled when unavailable.
    let entity_dir = models_base.join("entity-classifier");
    println!("cargo:rerun-if-changed={}", entity_dir.display());

    if entity_dir.join("model.safetensors").exists() && entity_dir.join("config.json").exists() {
        let model_path = portable_path(&entity_dir.join("model.safetensors"));
        let config_path = portable_path(&entity_dir.join("config.json"));

        code.push_str("\n// Entity classifier (full_name demotion gate, NNFT-152)\n");
        code.push_str("pub const HAS_ENTITY_CLASSIFIER: bool = true;\n");
        code.push_str(&format!(
            "pub const ENTITY_MODEL: &[u8] = include_bytes!(\"{model_path}\");\n"
        ));
        code.push_str(&format!(
            "pub const ENTITY_CONFIG: &[u8] = include_bytes!(\"{config_path}\");\n"
        ));

        println!(
            "cargo:warning=Embedding entity classifier from {}",
            entity_dir.display()
        );
    } else {
        code.push_str("\n// Entity classifier not available — full_name demotion disabled\n");
        code.push_str("pub const HAS_ENTITY_CLASSIFIER: bool = false;\n");
        code.push_str("pub const ENTITY_MODEL: &[u8] = &[];\n");
        code.push_str("pub const ENTITY_CONFIG: &[u8] = &[];\n");
    }

    fs::write(&dest, code).unwrap_or_else(|e| panic!("Failed to write {}: {}", dest.display(), e));
}

/// Generate embeds for a flat CharCNN model (single model.safetensors + labels.json + config.yaml).
#[cfg(feature = "embed-models")]
fn generate_flat_embeds(model_dir: &Path, code: &mut String) {
    assert!(
        model_dir.join("model.safetensors").exists(),
        "Flat model not found at {:?}. Run from workspace root or disable embed-models feature.",
        model_dir
    );

    let weights_path = portable_path(&model_dir.join("model.safetensors"));
    let labels_path = portable_path(&model_dir.join("labels.json"));
    let config_path = portable_path(&model_dir.join("config.yaml"));

    code.push_str(&format!(
        "pub const FLAT_WEIGHTS: &[u8] = include_bytes!(\"{weights_path}\");\n"
    ));
    code.push_str(&format!(
        "pub const FLAT_LABELS: &[u8] = include_bytes!(\"{labels_path}\");\n"
    ));
    code.push_str(&format!(
        "pub const FLAT_CONFIG: &[u8] = include_bytes!(\"{config_path}\");\n"
    ));
}

/// Generate embeds for a tiered model (tier_graph.json + multiple tier subdirectories).
///
/// Produces:
/// - `TIER_GRAPH: &[u8]` — the tier_graph.json bytes
/// - `get_tiered_model_data(dir: &str) -> Option<(&[u8], &[u8], &[u8])>` — lookup function
#[cfg(feature = "embed-models")]
fn generate_tiered_embeds(model_dir: &Path, code: &mut String) {
    let graph_path = model_dir.join("tier_graph.json");
    assert!(
        graph_path.exists(),
        "Tiered model tier_graph.json not found at {:?}.",
        model_dir
    );

    // Embed tier_graph.json
    let graph_portable = portable_path(&graph_path);
    code.push_str(&format!(
        "pub const TIER_GRAPH: &[u8] = include_bytes!(\"{graph_portable}\");\n\n"
    ));

    // Find all tier subdirectories that contain model.safetensors
    let mut tier_dirs: Vec<(String, PathBuf)> = Vec::new();
    for entry in fs::read_dir(model_dir).expect("Failed to read model directory") {
        let entry = entry.expect("Failed to read directory entry");
        let path = entry.path();
        if path.is_dir() && path.join("model.safetensors").exists() {
            let dir_name = entry.file_name().to_string_lossy().to_string();
            tier_dirs.push((dir_name, path));
        }
    }
    tier_dirs.sort_by(|a, b| a.0.cmp(&b.0));

    // Generate the lookup function
    code.push_str(
        "pub fn get_tiered_model_data(dir_name: &str) -> Option<(&'static [u8], &'static [u8], &'static [u8])> {\n",
    );
    code.push_str("    match dir_name {\n");

    for (dir_name, dir_path) in &tier_dirs {
        let weights = portable_path(&dir_path.join("model.safetensors"));
        let labels = portable_path(&dir_path.join("labels.json"));
        let config = portable_path(&dir_path.join("config.yaml"));

        code.push_str(&format!(
            "        \"{dir_name}\" => Some((\n\
             \x20           include_bytes!(\"{weights}\"),\n\
             \x20           include_bytes!(\"{labels}\"),\n\
             \x20           include_bytes!(\"{config}\"),\n\
             \x20       )),\n"
        ));
    }

    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n");
}
