//! Build script for finetype CLI.
//!
//! When the `embed-models` feature is enabled, embeds the flat CharCNN model
//! (weights, labels, config) and taxonomy YAML files at compile time so the
//! binary works standalone.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let workspace_root = PathBuf::from(&manifest_dir)
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf();

    // Models live at workspace root: models/default -> char-cnn-v4/
    let models_base = workspace_root.join("models");
    let labels_base = workspace_root.join("labels");

    println!("cargo:rerun-if-changed={}", models_base.display());
    println!("cargo:rerun-if-changed={}", labels_base.display());

    #[cfg(feature = "embed-models")]
    generate_embedded_models(&models_base, &labels_base);

    #[cfg(not(feature = "embed-models"))]
    {
        let _ = models_base;
        let _ = labels_base;
    }
}

#[cfg(feature = "embed-models")]
fn generate_embedded_models(models_base: &std::path::Path, labels_base: &std::path::Path) {
    // Follow the models/default symlink to find the active model
    let default_link = models_base.join("default");
    let flat_dir = if default_link.exists() {
        std::fs::read_link(&default_link)
            .map(|target| {
                if target.is_relative() {
                    models_base.join(target)
                } else {
                    target
                }
            })
            .unwrap_or_else(|_| models_base.join("char-cnn-v4"))
    } else {
        models_base.join("char-cnn-v4")
    };

    assert!(
        flat_dir.join("model.safetensors").exists(),
        "Flat model not found at {:?}. Run from workspace root or disable embed-models feature.",
        flat_dir
    );

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = PathBuf::from(&out_dir).join("embedded_models.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit\n\n");

    // Embed model files
    let weights_path = flat_dir.join("model.safetensors").canonicalize().unwrap();
    let labels_path = flat_dir.join("labels.json").canonicalize().unwrap();
    let config_path = flat_dir.join("config.yaml").canonicalize().unwrap();

    code.push_str(&format!(
        "pub const FLAT_WEIGHTS: &[u8] = include_bytes!(\"{}\");\n",
        weights_path.display()
    ));
    code.push_str(&format!(
        "pub const FLAT_LABELS: &[u8] = include_bytes!(\"{}\");\n",
        labels_path.display()
    ));
    code.push_str(&format!(
        "pub const FLAT_CONFIG: &[u8] = include_bytes!(\"{}\");\n",
        config_path.display()
    ));

    // Embed taxonomy YAML files
    let mut yaml_paths: Vec<_> = fs::read_dir(labels_base)
        .expect("Failed to read labels directory")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| {
            p.file_name()
                .and_then(|n| n.to_str())
                .map(|n| n.starts_with("definitions_") && n.ends_with(".yaml"))
                .unwrap_or(false)
        })
        .collect();
    yaml_paths.sort();

    code.push_str(&format!(
        "\npub const TAXONOMY_YAMLS: &[&str] = &[\n"
    ));
    for path in &yaml_paths {
        let canonical = path.canonicalize().unwrap();
        code.push_str(&format!(
            "    include_str!(\"{}\"),\n",
            canonical.display()
        ));
    }
    code.push_str("];\n");

    fs::write(&dest, code)
        .unwrap_or_else(|e| panic!("Failed to write {}: {}", dest.display(), e));
}
