#!/usr/bin/env bash
set -euo pipefail

# runpod_launch.sh — Provision a RunPod RTX 4090 pod for FineType autoresearch
# Covers: ac-11 (pod + self-destruct), ac-12 (SSH), ac-13 (initial setup)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_FILE="$PROJECT_ROOT/.runpod_config.env"
SSH_FILE="$PROJECT_ROOT/.runpod_ssh.env"

# Defaults
POD_NAME="finetype-autoresearch"
GPU_ID="NVIDIA GeForce RTX 4090"
CLOUD_TYPE="COMMUNITY"
TEMPLATE_ID="runpod-torch-v280"  # Official Pytorch 2.8.0 template (CUDA 12.8.1)
CONTAINER_DISK_GB=20
VOLUME_SIZE_GB=50
VOLUME_NAME="finetype-training"
MAX_RUNTIME_HOURS="${MAX_RUNTIME_HOURS:-10}"
COST_PER_HR="0.40"
# Regions with known 4090 availability
PREFERRED_REGIONS="US-TX-3,US-IL-1,US-NC-1,EU-RO-1,EU-CZ-1"
FINETYPE_VERSION="v0.6.12"

SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10"

log() { echo "[$(date '+%H:%M:%S')] $*"; }
err() { echo "[$(date '+%H:%M:%S')] ERROR: $*" >&2; }
die() { err "$*"; exit 1; }

# ─── Prerequisite checks ────────────────────────────────────────────────────

log "Checking prerequisites..."

command -v runpodctl >/dev/null 2>&1 || die "runpodctl not found. Install: https://github.com/runpod/runpodctl"
command -v jq >/dev/null 2>&1 || die "jq not found. Install: sudo apt install jq"
command -v rsync >/dev/null 2>&1 || die "rsync not found."

# Verify runpodctl is authenticated (pod list should not error)
if ! runpodctl pod list >/dev/null 2>&1; then
    die "runpodctl not authenticated. Run: runpodctl config"
fi
log "  runpodctl authenticated"

# Check SSH key is registered with RunPod
LOCAL_PUBKEY_FILE=""
if [ -f "$HOME/.ssh/id_ed25519.pub" ]; then
    LOCAL_PUBKEY_FILE="$HOME/.ssh/id_ed25519.pub"
elif [ -f "$HOME/.ssh/id_rsa.pub" ]; then
    LOCAL_PUBKEY_FILE="$HOME/.ssh/id_rsa.pub"
else
    die "No SSH public key found at ~/.ssh/id_ed25519.pub or ~/.ssh/id_rsa.pub"
fi

LOCAL_PUBKEY=$(cat "$LOCAL_PUBKEY_FILE")
LOCAL_KEY_TYPE=$(echo "$LOCAL_PUBKEY" | awk '{print $1}')
REGISTERED_KEYS=$(runpodctl ssh list-keys 2>/dev/null)
# Check if our key type is among registered keys
if ! echo "$REGISTERED_KEYS" | jq -e --arg kt "$LOCAL_KEY_TYPE" '.keys[] | select(.type == $kt)' >/dev/null 2>&1; then
    log "  Registering SSH key with RunPod..."
    runpodctl ssh add-key --key-file "$LOCAL_PUBKEY_FILE"
    log "  SSH key registered"
else
    log "  SSH key already registered"
fi

# ─── Network volume ─────────────────────────────────────────────────────────

VOLUME_ID=""

# Check for existing config
if [ -f "$CONFIG_FILE" ]; then
    # shellcheck source=/dev/null
    source "$CONFIG_FILE"
    VOLUME_ID="${VOLUME_ID:-}"
fi

# Verify volume still exists (may have been deleted)
if [ -n "$VOLUME_ID" ]; then
    if ! runpodctl network-volume get "$VOLUME_ID" >/dev/null 2>&1; then
        log "  Configured volume $VOLUME_ID no longer exists, will create new one"
        VOLUME_ID=""
    else
        log "  Using existing network volume: $VOLUME_ID"
    fi
fi

# Check for volume by name in existing volumes
if [ -z "$VOLUME_ID" ]; then
    EXISTING_VOL=$(runpodctl network-volume list 2>/dev/null | jq -r --arg name "$VOLUME_NAME" '.[] | select(.name == $name) | .id' 2>/dev/null || echo "")
    if [ -n "$EXISTING_VOL" ]; then
        VOLUME_ID="$EXISTING_VOL"
        log "  Found existing network volume by name: $VOLUME_ID"
    fi
fi

# Create volume if needed
if [ -z "$VOLUME_ID" ]; then
    log "Creating network volume '$VOLUME_NAME' (${VOLUME_SIZE_GB}GB)..."

    # Try preferred regions in order
    IFS=',' read -ra REGIONS <<< "$PREFERRED_REGIONS"
    for REGION in "${REGIONS[@]}"; do
        log "  Trying region: $REGION"
        VOL_OUTPUT=$(runpodctl network-volume create \
            --name "$VOLUME_NAME" \
            --size "$VOLUME_SIZE_GB" \
            --data-center-id "$REGION" 2>&1) || true

        VOL_ID_CANDIDATE=$(echo "$VOL_OUTPUT" | jq -r '.id // empty' 2>/dev/null || echo "")
        if [ -n "$VOL_ID_CANDIDATE" ]; then
            VOLUME_ID="$VOL_ID_CANDIDATE"
            log "  Volume created in $REGION: $VOLUME_ID"
            break
        fi
        log "  Region $REGION failed, trying next..."
    done

    if [ -z "$VOLUME_ID" ]; then
        die "Failed to create network volume in any region"
    fi
fi

# Save config early (volume ID is the most important thing to persist)
cat > "$CONFIG_FILE" <<EOF
# RunPod configuration — generated by runpod_launch.sh
VOLUME_ID=$VOLUME_ID
VOLUME_NAME=$VOLUME_NAME
MAX_RUNTIME_HOURS=$MAX_RUNTIME_HOURS
PREFERRED_REGIONS=$PREFERRED_REGIONS
EOF
log "  Config saved to $CONFIG_FILE"

# ─── Create pod ──────────────────────────────────────────────────────────────

log "Creating pod '$POD_NAME' with $GPU_ID..."

# Check for existing running pod with same name
EXISTING_POD=$(runpodctl pod list --name "$POD_NAME" 2>/dev/null | jq -r '.[0].id // empty' 2>/dev/null || echo "")
if [ -n "$EXISTING_POD" ]; then
    log "  Found existing pod: $EXISTING_POD"
    EXISTING_STATUS=$(runpodctl pod get "$EXISTING_POD" 2>/dev/null | jq -r '.desiredStatus // .status // "UNKNOWN"' 2>/dev/null || echo "UNKNOWN")
    if [ "$EXISTING_STATUS" = "RUNNING" ]; then
        log "  Pod is already RUNNING. Skipping creation."
        POD_ID="$EXISTING_POD"
    else
        log "  Pod status: $EXISTING_STATUS. Will create a new one."
        EXISTING_POD=""
    fi
fi

if [ -z "${POD_ID:-}" ]; then
    POD_OUTPUT=$(runpodctl pod create \
        --template-id "$TEMPLATE_ID" \
        --gpu-id "$GPU_ID" \
        --cloud-type "$CLOUD_TYPE" \
        --network-volume-id "$VOLUME_ID" \
        --container-disk-in-gb "$CONTAINER_DISK_GB" \
        --name "$POD_NAME" \
        --ports "22/tcp" 2>&1)

    POD_ID=$(echo "$POD_OUTPUT" | jq -r '.id // empty' 2>/dev/null || echo "")
    if [ -z "$POD_ID" ]; then
        err "Pod creation output: $POD_OUTPUT"
        die "Failed to create pod — could not parse pod ID from output"
    fi
    log "  Pod created: $POD_ID"
fi

# ─── Wait for pod to be RUNNING ─────────────────────────────────────────────

log "Waiting for pod $POD_ID to reach RUNNING state..."
MAX_WAIT=300  # 5 minutes
WAITED=0
POLL_INTERVAL=10

while [ $WAITED -lt $MAX_WAIT ]; do
    POD_INFO=$(runpodctl pod get "$POD_ID" 2>/dev/null || echo "{}")
    POD_STATUS=$(echo "$POD_INFO" | jq -r '.desiredStatus // .status // "UNKNOWN"' 2>/dev/null || echo "UNKNOWN")
    RUNTIME_STATUS=$(echo "$POD_INFO" | jq -r '.runtime.uptimeInSeconds // 0' 2>/dev/null || echo "0")

    if [ "$POD_STATUS" = "RUNNING" ] && [ "$RUNTIME_STATUS" != "0" ] && [ "$RUNTIME_STATUS" != "null" ]; then
        log "  Pod is RUNNING (uptime: ${RUNTIME_STATUS}s)"
        break
    fi

    log "  Status: $POD_STATUS (waited ${WAITED}s/${MAX_WAIT}s)"
    sleep "$POLL_INTERVAL"
    WAITED=$((WAITED + POLL_INTERVAL))
done

if [ $WAITED -ge $MAX_WAIT ]; then
    die "Pod did not reach RUNNING state within ${MAX_WAIT}s"
fi

# ─── Parse SSH connection info ───────────────────────────────────────────────

log "Fetching SSH connection details..."

# Give SSH proxy a moment to register
sleep 5

SSH_INFO=$(runpodctl ssh info "$POD_ID" 2>/dev/null || echo "{}")
POD_HOST=$(echo "$SSH_INFO" | jq -r '.host // empty' 2>/dev/null || echo "")
POD_PORT=$(echo "$SSH_INFO" | jq -r '.port // empty' 2>/dev/null || echo "")

# Fallback: parse from pod runtime info
if [ -z "$POD_HOST" ] || [ -z "$POD_PORT" ]; then
    log "  ssh info returned incomplete data, trying pod get..."
    POD_INFO=$(runpodctl pod get "$POD_ID" 2>/dev/null || echo "{}")

    # Try parsing SSH connection from runtime ports
    POD_HOST=$(echo "$POD_INFO" | jq -r '.runtime.ports[]? | select(.privatePort == 22) | .ip // empty' 2>/dev/null || echo "")
    POD_PORT=$(echo "$POD_INFO" | jq -r '.runtime.ports[]? | select(.privatePort == 22) | .publicPort // empty' 2>/dev/null || echo "")
fi

if [ -z "$POD_HOST" ] || [ -z "$POD_PORT" ]; then
    # Last resort: try the ssh command string
    SSH_CMD=$(echo "$SSH_INFO" | jq -r '.sshCommand // empty' 2>/dev/null || echo "")
    if [ -n "$SSH_CMD" ]; then
        POD_HOST=$(echo "$SSH_CMD" | grep -oP '(?<=@)[\w\.\-]+' || echo "")
        POD_PORT=$(echo "$SSH_CMD" | grep -oP '(?<=-p )\d+' || echo "")
    fi
fi

if [ -z "$POD_HOST" ] || [ -z "$POD_PORT" ]; then
    err "SSH info output: $SSH_INFO"
    err "Pod info: $(runpodctl pod get "$POD_ID" 2>/dev/null)"
    die "Could not determine SSH host/port for pod $POD_ID"
fi

log "  SSH: root@$POD_HOST:$POD_PORT"

# Write SSH config
cat > "$SSH_FILE" <<EOF
# RunPod SSH connection — generated by runpod_launch.sh
POD_ID=$POD_ID
POD_HOST=$POD_HOST
POD_PORT=$POD_PORT
POD_COST_PER_HR=$COST_PER_HR
POD_CREATED=$(date +%s)
VOLUME_ID=$VOLUME_ID
MAX_RUNTIME_HOURS=$MAX_RUNTIME_HOURS
EOF
log "  SSH config saved to $SSH_FILE"

# ─── SSH helper function ────────────────────────────────────────────────────

pod_ssh() {
    ssh -p "$POD_PORT" $SSH_OPTS "root@$POD_HOST" "$@"
}

pod_rsync() {
    rsync -az -e "ssh -p $POD_PORT $SSH_OPTS" "$@"
}

# ─── Wait for SSH to be ready ───────────────────────────────────────────────

log "Waiting for SSH to become available..."
SSH_READY=false
for i in $(seq 1 30); do
    if pod_ssh "echo ok" >/dev/null 2>&1; then
        SSH_READY=true
        break
    fi
    sleep 5
done

if [ "$SSH_READY" != "true" ]; then
    die "SSH not available after 150s. Check pod status: runpodctl pod get $POD_ID"
fi
log "  SSH ready"

# ─── Initial pod setup ──────────────────────────────────────────────────────

log "Setting up pod environment..."

# 1. Clone finetype repo (for eval datasets)
log "  Cloning finetype repo..."
pod_ssh "if [ ! -d /workspace/finetype ]; then git clone --depth 1 https://github.com/meridian-online/finetype.git /workspace/finetype; else echo 'Repo already exists'; fi"

# 2. Download finetype binary to network volume
log "  Installing finetype binary..."
pod_ssh "
    if [ -x /workspace/bin/finetype ]; then
        echo 'finetype binary already installed'
    else
        mkdir -p /workspace/bin
        cd /tmp
        curl -sL https://github.com/meridian-online/finetype/releases/download/${FINETYPE_VERSION}/finetype-${FINETYPE_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar xz
        mv finetype /workspace/bin/finetype
        chmod +x /workspace/bin/finetype
        echo 'finetype binary installed'
    fi
    /workspace/bin/finetype --version
"

# 3. Create research workspace
log "  Creating research workspace..."
pod_ssh "mkdir -p /workspace/research"

# 4. Sync research files from Beelink
if [ -d "$PROJECT_ROOT/research" ]; then
    log "  Syncing research files to pod..."
    pod_rsync "$PROJECT_ROOT/research/" "root@$POD_HOST:/workspace/research/"
else
    log "  No research/ directory found locally — skipping sync"
fi

# 5. Install Python dependencies on pod
log "  Installing Python dependencies..."
pod_ssh "
    cd /workspace/research
    if [ -f pyproject.toml ]; then
        if command -v uv >/dev/null 2>&1; then
            uv sync 2>&1 | tail -3
        else
            pip install uv 2>&1 | tail -1
            uv sync 2>&1 | tail -3
        fi
    elif [ -f requirements.txt ]; then
        pip install -r requirements.txt 2>&1 | tail -3
    else
        echo 'No pyproject.toml or requirements.txt — skipping pip install'
    fi
"

# ─── Self-destruct timer (ac-11, zombie protection layer 1) ─────────────────

log "Starting self-destruct timer (${MAX_RUNTIME_HOURS}h)..."
SELF_DESTRUCT_SECS=$((MAX_RUNTIME_HOURS * 3600))

# Install runpodctl on the pod if not present, then start timer
pod_ssh "
    # Install runpodctl on pod for self-destruct
    if ! command -v runpodctl >/dev/null 2>&1; then
        curl -sL https://github.com/runpod/runpodctl/releases/latest/download/runpodctl-linux-amd64 -o /usr/local/bin/runpodctl
        chmod +x /usr/local/bin/runpodctl
    fi

    # Start self-destruct timer as a background process
    nohup bash -c '
        sleep $SELF_DESTRUCT_SECS
        echo \"[SELF-DESTRUCT] Pod runtime exceeded ${MAX_RUNTIME_HOURS}h — stopping pod\" >> /workspace/research/run.log
        runpodctl pod stop $POD_ID 2>/dev/null || true
    ' > /tmp/self_destruct.log 2>&1 &
    echo \"Self-destruct PID: \$!\"
"
log "  Self-destruct timer set for ${MAX_RUNTIME_HOURS}h (${SELF_DESTRUCT_SECS}s)"

# ─── Install watchdog cron on Beelink (ac-23) ───────────────────────────────

log "Installing watchdog cron job..."
WATCHDOG_SCRIPT="$SCRIPT_DIR/runpod_watchdog.sh"
WATCHDOG_LOG="/var/log/runpod_watchdog.log"
CRON_ENTRY="*/30 * * * * $WATCHDOG_SCRIPT >> $WATCHDOG_LOG 2>&1"

# Remove any existing watchdog entry, then add fresh one
(crontab -l 2>/dev/null | grep -v "runpod_watchdog.sh" || true; echo "$CRON_ENTRY") | crontab -
log "  Watchdog cron installed (every 30 min)"

# ─── Initialize budget tracking ─────────────────────────────────────────────

BUDGET_FILE="$PROJECT_ROOT/budget.json"
if [ ! -f "$BUDGET_FILE" ]; then
    cat > "$BUDGET_FILE" <<BUDGET_EOF
{
  "budget_cap": 40.00,
  "alert_threshold": 35.00,
  "sessions": [],
  "total_spend": 0.00
}
BUDGET_EOF
    log "  Created budget.json"
fi

# Add this session to budget
UPDATED_BUDGET=$(jq --arg pid "$POD_ID" --arg start "$(date +%s)" --arg cph "$COST_PER_HR" \
    '.sessions += [{"pod_id": $pid, "start": ($start | tonumber), "end": null, "cost_per_hr": ($cph | tonumber)}]' \
    "$BUDGET_FILE")
echo "$UPDATED_BUDGET" > "$BUDGET_FILE"
log "  Session added to budget.json"

# ─── Summary ─────────────────────────────────────────────────────────────────

GPU_INFO=$(pod_ssh "nvidia-smi --query-gpu=name,memory.total --format=csv,noheader" 2>/dev/null || echo "unknown")

echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "  RunPod pod ready for autoresearch"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "  Pod ID:        $POD_ID"
echo "  Pod name:      $POD_NAME"
echo "  GPU:           $GPU_INFO"
echo "  SSH:           ssh -p $POD_PORT $SSH_OPTS root@$POD_HOST"
echo "  Volume:        $VOLUME_ID ($VOLUME_NAME)"
echo "  Cost:          ~\$$COST_PER_HR/hr ($CLOUD_TYPE)"
echo "  Max runtime:   ${MAX_RUNTIME_HOURS}h (self-destruct + watchdog)"
echo "  Config:        $SSH_FILE"
echo ""
echo "  Quick commands:"
echo "    $SCRIPT_DIR/runpod_sync.sh push     # Sync code to pod"
echo "    $SCRIPT_DIR/runpod_sync.sh pull     # Pull results back"
echo "    $SCRIPT_DIR/runpod_sync.sh run CMD  # Run command on pod"
echo "    $SCRIPT_DIR/runpod_stop.sh          # Graceful shutdown"
echo "    $SCRIPT_DIR/runpod_budget.sh status # Check budget"
echo ""
echo "════════════════════════════════════════════════════════════════════"
