//! FineType DuckDB Extension
//!
//! Provides scalar functions for semantic type classification:
//! - `finetype_version()` — Returns the extension version
//! - `finetype(value)` — Classify a single value, returns the semantic type label
//! - `finetype(list(values))` — Column-level classification with disambiguation
//! - `finetype(list(values), header)` — Column-level classification with header hint
//! - `finetype_detail(value)` — Classify with detail: returns JSON with type, confidence, DuckDB type
//! - `finetype_detail(list(values))` — Column-level classification with full JSON detail
//! - `finetype_cast(value)` — Normalize a value for safe TRY_CAST (dates → ISO, booleans → true/false, etc.)
//! - `finetype_unpack(json)` — Recursively classify JSON fields, returns annotated JSON

use duckdb::core::{DataChunkHandle, Inserter, LogicalTypeHandle, LogicalTypeId};
use duckdb::vscalar::{ScalarFunctionSignature, VScalar};
use duckdb::vtab::arrow::WritableVector;
use duckdb::{duckdb_entrypoint_c_api, Result};
use std::error::Error;
use std::ffi::CString;
use std::path::PathBuf;
use std::sync::OnceLock;

use finetype_core::Taxonomy;
use finetype_model::{ColumnClassifier, ColumnConfig, MultiBranchClassifier};

// Embedded taxonomy YAML definitions (generated by build.rs from labels/).
include!(concat!(env!("OUT_DIR"), "/embedded_taxonomy.rs"));

mod column_fn;
mod normalize;
mod spike;
mod type_mapping;
mod unpack;
mod validate;

// ═══════════════════════════════════════════════════════════════════════════════
// RUNTIME MODEL LOADING
// ═══════════════════════════════════════════════════════════════════════════════

/// Extension name and version.
const EXTENSION_VERSION: &str = env!("CARGO_PKG_VERSION");

/// HuggingFace repository for the default FineType multi-branch model.
const HF_REPO: &str = "meridian-online/finetype-model";

/// Files required for the multi-branch model.
const MODEL_FILES: &[&str] = &["model.safetensors", "label_map.json", "config.json"];

/// Model2Vec files (embed + header branches) — fetched from the `model2vec/`
/// subdirectory of the same HuggingFace repo.
const M2V_TOKENIZER: &str = "model2vec/tokenizer.json";
const M2V_MODEL: &str = "model2vec/model.safetensors";

/// Global column classifier backed by multi-branch model.
/// Initialized on first finetype() call, loaded at runtime from
/// HuggingFace Hub or a local directory.
static COLUMN_CLASSIFIER: OnceLock<ColumnClassifier> = OnceLock::new();

/// Resolve the model directory: check `FINETYPE_MODEL_DIR` env var first,
/// then fall back to downloading from HuggingFace Hub.
fn resolve_model_dir() -> std::result::Result<PathBuf, Box<dyn Error>> {
    // 1. Check env var for local path override
    if let Ok(dir) = std::env::var("FINETYPE_MODEL_DIR") {
        let path = PathBuf::from(&dir);
        if path.join("model.safetensors").exists() {
            tracing::info!("Loading FineType model from local path: {}", dir);
            return Ok(path);
        }
        return Err(format!(
            "FINETYPE_MODEL_DIR={} does not contain model.safetensors",
            dir
        )
        .into());
    }

    // 2. Download from HuggingFace Hub (cached after first download)
    tracing::info!(
        "Downloading FineType model from HuggingFace Hub: {}",
        HF_REPO
    );
    let repo = hf_hub::Repo::new(HF_REPO.to_string(), hf_hub::RepoType::Model);
    let api = hf_hub::api::sync::Api::new()?;
    let api = api.repo(repo);

    // Download all required files — hf_hub caches them automatically.
    // model.safetensors is first, and being a top-level file its parent is the
    // snapshot root we return as the model dir.
    let mut model_dir = None;
    for filename in MODEL_FILES {
        let path = api.get(filename)?;
        if model_dir.is_none() {
            // All files from the same repo land in the same cache directory
            model_dir = path.parent().map(|p| p.to_path_buf());
        }
    }

    // The embed + header branches require Model2Vec resources, which
    // MultiBranchClassifier::load looks for at `<model_dir>/model2vec/`. hf_hub
    // preserves the repo subpath, so fetching `model2vec/*` lands the files in
    // `<snapshot>/model2vec/` — co-located exactly where the loader expects.
    // Without this the model load panics anywhere the cwd has no
    // `models/model2vec/` (i.e. any real user invocation).
    api.get(M2V_TOKENIZER)?;
    api.get(M2V_MODEL)?;

    model_dir.ok_or_else(|| "Failed to determine model cache directory".into())
}

/// Initialize or get the global column classifier backed by multi-branch model.
fn get_column_classifier() -> &'static ColumnClassifier {
    COLUMN_CLASSIFIER.get_or_init(|| {
        let model_dir = resolve_model_dir().expect("Failed to resolve FineType model directory");
        let mb = MultiBranchClassifier::load(&model_dir)
            .expect("Failed to load multi-branch model from resolved directory");
        let config = ColumnConfig {
            sample_size: 100,
            ..Default::default()
        };
        let mut cc = ColumnClassifier::with_multi_branch(mb, config);
        // Validation-based disambiguation needs the taxonomy with compiled
        // validators — without it the Sharpen stage cannot confirm predicted
        // types and column results collapse toward representation.text.plain_text.
        match Taxonomy::from_yamls(TAXONOMY_YAMLS) {
            Ok(mut taxonomy) => {
                taxonomy.compile_validators();
                taxonomy.compile_locale_validators();
                cc.set_taxonomy(taxonomy);
            }
            Err(e) => tracing::warn!("Failed to build embedded taxonomy: {e}"),
        }
        cc
    })
}

// ═══════════════════════════════════════════════════════════════════════════════
// VARCHAR HELPERS
// ═══════════════════════════════════════════════════════════════════════════════

/// Read a VARCHAR value from a DuckDB data chunk at a specific column and row.
///
/// Returns None if the value is NULL.
unsafe fn read_varchar(
    input: &mut DataChunkHandle,
    col_idx: usize,
    row_idx: usize,
) -> Option<String> {
    use libduckdb_sys::*;

    let raw_chunk = input.get_ptr();
    let vector = duckdb_data_chunk_get_vector(raw_chunk, col_idx as idx_t);

    // Check validity (NULL check)
    let validity = duckdb_vector_get_validity(vector);
    if !validity.is_null() {
        let entry = row_idx / 64;
        let bit = row_idx % 64;
        let mask = *validity.add(entry);
        if (mask >> bit) & 1 == 0 {
            return None;
        }
    }

    // Read string data
    let data = duckdb_vector_get_data(vector) as *const duckdb_string_t;
    let str_val = *data.add(row_idx);

    let (ptr, len) = if duckdb_string_is_inlined(str_val) {
        (
            str_val.value.inlined.inlined.as_ptr() as *const u8,
            str_val.value.inlined.length as usize,
        )
    } else {
        (
            str_val.value.pointer.ptr as *const u8,
            str_val.value.pointer.length as usize,
        )
    };

    if ptr.is_null() || len == 0 {
        return Some(String::new());
    }

    let bytes = std::slice::from_raw_parts(ptr, len);
    std::str::from_utf8(bytes).ok().map(|s| s.to_string())
}

// ═══════════════════════════════════════════════════════════════════════════════
// SCALAR FUNCTIONS
// ═══════════════════════════════════════════════════════════════════════════════

/// `finetype_version()` — Returns the FineType extension version string.
struct FineTypeVersion;

impl VScalar for FineTypeVersion {
    type State = ();

    unsafe fn invoke(
        _state: &Self::State,
        input: &mut DataChunkHandle,
        output: &mut dyn WritableVector,
    ) -> Result<(), Box<dyn Error>> {
        let len = input.len();
        let output_vec = output.flat_vector();
        let version = CString::new(format!("finetype {}", EXTENSION_VERSION))?;
        for i in 0..len {
            output_vec.insert(i, version.clone());
        }
        Ok(())
    }

    fn signatures() -> Vec<ScalarFunctionSignature> {
        vec![ScalarFunctionSignature::exact(
            vec![],
            LogicalTypeHandle::from(LogicalTypeId::Varchar),
        )]
    }
}

/// `finetype(value VARCHAR) → VARCHAR` — Semantic type classification.
/// `finetype(list(values) LIST<VARCHAR>) → VARCHAR` — Explicit column classification.
/// `finetype(list(values) LIST<VARCHAR>, header VARCHAR) → VARCHAR` — Column with header hint.
///
/// Classifies data as a semantic type (e.g. "datetime.date.iso", "identity.person.email").
///
/// In scalar mode (`finetype(col)`), the function automatically uses the DuckDB
/// processing chunk (~2048 rows) as a sample for column-level disambiguation.
/// This means majority vote + disambiguation rules (date formats, coordinates,
/// boolean subtypes, categorical detection, numeric range, etc.) are applied
/// even without an explicit `list()` wrapper.
///
/// The `list()` overload gives explicit control over the sample — useful with
/// GROUP BY to classify each group independently, or when you want the full
/// column rather than a chunk-sized sample.
struct FineType;

impl VScalar for FineType {
    type State = ();

    unsafe fn invoke(
        _state: &Self::State,
        input: &mut DataChunkHandle,
        output: &mut dyn WritableVector,
    ) -> Result<(), Box<dyn Error>> {
        // Dispatch based on input type: VARCHAR vs LIST<VARCHAR>
        if column_fn::is_list_input(input) {
            return column_fn::invoke_column_label(input, output);
        }

        // Scalar path: use the chunk as a column sample for disambiguation.
        // Collect all non-null, non-empty values, run column classification,
        // and write the consensus label for every row.
        let len = input.len();
        let mut output_vec = output.flat_vector();

        let mut non_null_indices: Vec<usize> = Vec::with_capacity(len);
        let mut texts: Vec<String> = Vec::with_capacity(len);

        for i in 0..len {
            if let Some(text) = read_varchar(input, 0, i) {
                if !text.is_empty() {
                    non_null_indices.push(i);
                    texts.push(text);
                } else {
                    let cstr = CString::new("unknown")?;
                    output_vec.insert(i, cstr);
                }
            } else {
                output_vec.set_null(i);
            }
        }

        if !texts.is_empty() {
            let col_result = column_fn::classify_column(&texts)?;
            let label = CString::new(col_result.label.as_str())?;
            for idx in &non_null_indices {
                output_vec.insert(*idx, label.clone());
            }
        }

        Ok(())
    }

    fn signatures() -> Vec<ScalarFunctionSignature> {
        let varchar = LogicalTypeHandle::from(LogicalTypeId::Varchar);
        let list_varchar = LogicalTypeHandle::list(&varchar);

        vec![
            // finetype(value VARCHAR) → VARCHAR
            ScalarFunctionSignature::exact(
                vec![LogicalTypeHandle::from(LogicalTypeId::Varchar)],
                LogicalTypeHandle::from(LogicalTypeId::Varchar),
            ),
            // finetype(list(values) LIST<VARCHAR>) → VARCHAR
            ScalarFunctionSignature::exact(
                vec![list_varchar],
                LogicalTypeHandle::from(LogicalTypeId::Varchar),
            ),
            // finetype(list(values) LIST<VARCHAR>, header VARCHAR) → VARCHAR
            ScalarFunctionSignature::exact(
                vec![
                    LogicalTypeHandle::list(&LogicalTypeHandle::from(LogicalTypeId::Varchar)),
                    LogicalTypeHandle::from(LogicalTypeId::Varchar),
                ],
                LogicalTypeHandle::from(LogicalTypeId::Varchar),
            ),
        ]
    }
}

/// `finetype_detail(value VARCHAR) → VARCHAR` — Detailed semantic type classification.
/// `finetype_detail(list(values) LIST<VARCHAR>) → VARCHAR` — Explicit column detail.
/// `finetype_detail(list(values) LIST<VARCHAR>, header VARCHAR) → VARCHAR` — Column detail with header.
///
/// Returns a JSON object with classification details. In both scalar and list modes,
/// the output includes:
/// - `type`: semantic type label
/// - `confidence`: classification confidence (0.0 to 1.0)
/// - `duckdb_type`: recommended DuckDB CAST target type
/// - `samples`: number of values in the sample
/// - `disambiguation`: name of disambiguation rule applied (if any)
/// - `votes`: top vote distribution (label → fraction)
///
/// In scalar mode, the DuckDB processing chunk (~2048 rows) is used as the
/// column sample. The `list()` overload gives explicit control over the sample.
struct FineTypeDetail;

impl VScalar for FineTypeDetail {
    type State = ();

    unsafe fn invoke(
        _state: &Self::State,
        input: &mut DataChunkHandle,
        output: &mut dyn WritableVector,
    ) -> Result<(), Box<dyn Error>> {
        // Dispatch based on input type: VARCHAR vs LIST<VARCHAR>
        if column_fn::is_list_input(input) {
            return column_fn::invoke_column_detail(input, output);
        }

        // Scalar path: column classification over the chunk
        let len = input.len();
        let mut output_vec = output.flat_vector();

        let mut non_null_indices: Vec<usize> = Vec::with_capacity(len);
        let mut texts: Vec<String> = Vec::with_capacity(len);

        for i in 0..len {
            if let Some(text) = read_varchar(input, 0, i) {
                if !text.is_empty() {
                    non_null_indices.push(i);
                    texts.push(text);
                } else {
                    let cstr = CString::new(
                        r#"{"type":"unknown","confidence":0.0,"duckdb_type":"VARCHAR","samples":0}"#,
                    )?;
                    output_vec.insert(i, cstr);
                }
            } else {
                output_vec.set_null(i);
            }
        }

        if !texts.is_empty() {
            let col_result = column_fn::classify_column(&texts)?;
            let json = column_fn::format_column_result_json(&col_result);
            let cstr = CString::new(json)?;
            for idx in &non_null_indices {
                output_vec.insert(*idx, cstr.clone());
            }
        }

        Ok(())
    }

    fn signatures() -> Vec<ScalarFunctionSignature> {
        let varchar = LogicalTypeHandle::from(LogicalTypeId::Varchar);
        let list_varchar = LogicalTypeHandle::list(&varchar);

        vec![
            // finetype_detail(value VARCHAR) → VARCHAR
            ScalarFunctionSignature::exact(
                vec![LogicalTypeHandle::from(LogicalTypeId::Varchar)],
                LogicalTypeHandle::from(LogicalTypeId::Varchar),
            ),
            // finetype_detail(list(values) LIST<VARCHAR>) → VARCHAR
            ScalarFunctionSignature::exact(
                vec![list_varchar],
                LogicalTypeHandle::from(LogicalTypeId::Varchar),
            ),
            // finetype_detail(list(values) LIST<VARCHAR>, header VARCHAR) → VARCHAR
            ScalarFunctionSignature::exact(
                vec![
                    LogicalTypeHandle::list(&LogicalTypeHandle::from(LogicalTypeId::Varchar)),
                    LogicalTypeHandle::from(LogicalTypeId::Varchar),
                ],
                LogicalTypeHandle::from(LogicalTypeId::Varchar),
            ),
        ]
    }
}

/// `finetype_cast(value VARCHAR) → VARCHAR` — Normalize a value for safe casting.
///
/// Classifies the value, then normalizes it to a canonical form suitable for
/// DuckDB `TRY_CAST()`. Returns NULL if the value doesn't validate for its
/// detected type.
///
/// Examples:
/// - `finetype_cast('01/15/2024')` → `'2024-01-15'` (US date → ISO)
/// - `finetype_cast('Yes')` → `'true'` (boolean normalization)
/// - `finetype_cast('550E8400-...')` → `'550e8400-...'` (UUID lowercase)
/// - `finetype_cast('1,234')` → `'1234'` (strip formatting)
struct FineTypeCast;

impl VScalar for FineTypeCast {
    type State = ();

    unsafe fn invoke(
        _state: &Self::State,
        input: &mut DataChunkHandle,
        output: &mut dyn WritableVector,
    ) -> Result<(), Box<dyn Error>> {
        let col_classifier = get_column_classifier();
        let len = input.len();
        let mut output_vec = output.flat_vector();

        for i in 0..len {
            if let Some(text) = read_varchar(input, 0, i) {
                if text.is_empty() {
                    output_vec.set_null(i);
                    continue;
                }
                // Classify single value via column classifier (1-element column)
                match col_classifier.classify_column(std::slice::from_ref(&text)) {
                    Ok(result) => {
                        if let Some(normalized) = normalize::normalize(&text, &result.label) {
                            let cstr = CString::new(normalized)?;
                            output_vec.insert(i, cstr);
                        } else {
                            // Validation failed → NULL
                            output_vec.set_null(i);
                        }
                    }
                    Err(_) => {
                        // Classification error → pass through
                        let cstr = CString::new(text)?;
                        output_vec.insert(i, cstr);
                    }
                }
            }
            // NULL input → DuckDB handles NULL propagation
        }

        Ok(())
    }

    fn signatures() -> Vec<ScalarFunctionSignature> {
        vec![ScalarFunctionSignature::exact(
            vec![LogicalTypeHandle::from(LogicalTypeId::Varchar)],
            LogicalTypeHandle::from(LogicalTypeId::Varchar),
        )]
    }
}

/// `finetype_unpack(json_value VARCHAR) → VARCHAR` — Recursively infer types in JSON.
///
/// Parses a JSON string and classifies each scalar value. Returns annotated JSON
/// where each value is replaced with an object containing:
/// - `value`: the original value
/// - `type`: detected finetype label
/// - `confidence`: classification confidence (0.0 to 1.0)
/// - `duckdb_type`: recommended DuckDB type
///
/// Returns NULL for non-JSON input.
struct FineTypeUnpack;

impl VScalar for FineTypeUnpack {
    type State = ();

    unsafe fn invoke(
        _state: &Self::State,
        input: &mut DataChunkHandle,
        output: &mut dyn WritableVector,
    ) -> Result<(), Box<dyn Error>> {
        let col_classifier = get_column_classifier();
        let len = input.len();
        let mut output_vec = output.flat_vector();

        for i in 0..len {
            if let Some(text) = read_varchar(input, 0, i) {
                if text.is_empty() {
                    output_vec.set_null(i);
                    continue;
                }
                match unpack::unpack_json_column(&text, col_classifier) {
                    Some(annotated) => {
                        let cstr = CString::new(annotated)?;
                        output_vec.insert(i, cstr);
                    }
                    None => {
                        // Not valid JSON → NULL
                        output_vec.set_null(i);
                    }
                }
            }
        }

        Ok(())
    }

    fn signatures() -> Vec<ScalarFunctionSignature> {
        vec![ScalarFunctionSignature::exact(
            vec![LogicalTypeHandle::from(LogicalTypeId::Varchar)],
            LogicalTypeHandle::from(LogicalTypeId::Varchar),
        )]
    }
}

/// `finetype_validate(value VARCHAR, schema_json VARCHAR) → VARCHAR`
///
/// Validates a value against a JSON Schema fragment. Returns 'valid' if the value
/// passes, or the first validation error message if it fails.
///
/// The schema is parsed and cached for performance — the same schema string
/// is compiled only once across all rows.
///
/// Examples:
/// - `finetype_validate('test@example.com', '{"type":"string","pattern":"^[^@]+@[^@]+$"}')` → `'valid'`
/// - `finetype_validate('not-an-email', '{"type":"string","pattern":"^[^@]+@[^@]+$"}')` → error message
/// - `finetype_validate('abc', '{"type":"string","minLength":5}')` → error message
struct FineTypeValidate;

impl VScalar for FineTypeValidate {
    type State = ();

    unsafe fn invoke(
        _state: &Self::State,
        input: &mut DataChunkHandle,
        output: &mut dyn WritableVector,
    ) -> Result<(), Box<dyn Error>> {
        let len = input.len();
        let mut output_vec = output.flat_vector();

        for i in 0..len {
            let value = read_varchar(input, 0, i);
            let schema = read_varchar(input, 1, i);

            match (value, schema) {
                (Some(val), Some(sch)) => {
                    let result = validate::validate_value(&val, &sch);
                    let cstr = CString::new(result)?;
                    output_vec.insert(i, cstr);
                }
                _ => {
                    // NULL input → NULL output
                    output_vec.set_null(i);
                }
            }
        }

        Ok(())
    }

    fn signatures() -> Vec<ScalarFunctionSignature> {
        vec![ScalarFunctionSignature::exact(
            vec![
                LogicalTypeHandle::from(LogicalTypeId::Varchar),
                LogicalTypeHandle::from(LogicalTypeId::Varchar),
            ],
            LogicalTypeHandle::from(LogicalTypeId::Varchar),
        )]
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// ft_ CONVERGED SURFACE (spec 2026-06-03-duckdb-extension-table-verbs)
// ═══════════════════════════════════════════════════════════════════════════════

/// `ft_infer(value VARCHAR) → VARCHAR` — single-value semantic type probe.
///
/// "Profile with sample size 1": classifies each value on its own, with no
/// column context. Strictly weaker than `ft_profile` over a column sample — a
/// bare UUID, phone, or placeholder email only disambiguates when pooled with
/// its column siblings. Use `ft_profile(list(col))` for an accurate answer;
/// reach for `ft_infer` only to probe a single literal.
struct FineTypeInfer;

impl VScalar for FineTypeInfer {
    type State = ();

    unsafe fn invoke(
        _state: &Self::State,
        input: &mut DataChunkHandle,
        output: &mut dyn WritableVector,
    ) -> Result<(), Box<dyn Error>> {
        let col_classifier = get_column_classifier();
        let len = input.len();
        let mut output_vec = output.flat_vector();

        for i in 0..len {
            match read_varchar(input, 0, i) {
                Some(text) => {
                    let trimmed = text.trim();
                    if trimmed.is_empty() {
                        output_vec.insert(i, CString::new("unknown")?);
                        continue;
                    }
                    // Single-value column (sample size 1): no sibling context.
                    let label = match col_classifier.classify_column(&[trimmed.to_string()]) {
                        Ok(r) => r.label,
                        Err(_) => "unknown".to_string(),
                    };
                    output_vec.insert(i, CString::new(label)?);
                }
                None => output_vec.set_null(i),
            }
        }

        Ok(())
    }

    fn signatures() -> Vec<ScalarFunctionSignature> {
        vec![ScalarFunctionSignature::exact(
            vec![LogicalTypeHandle::from(LogicalTypeId::Varchar)],
            LogicalTypeHandle::from(LogicalTypeId::Varchar),
        )]
    }
}

/// `ft_profile(LIST<VARCHAR>) → STRUCT{type, confidence, duckdb_type}`
/// `ft_profile(LIST<VARCHAR>, header VARCHAR) → STRUCT{…}`
///
/// Column-level semantic type — the accurate path. Pools char/embed/stats/
/// validator signal across the values (the optional `header` feeds the header
/// branch). The aggregate `list()` assembles the sample on DuckDB's side; the
/// documented idiom is `SELECT ft_profile(list(col)) FROM t USING SAMPLE 100
/// ROWS` so the LIST is bounded before it is built. As a backstop, this scalar
/// reads at most `PROFILE_SAMPLE_CAP` (100) values from each list — the model
/// pools no more than that, so an unbounded `list(col)` over a huge column
/// bounds its model cost here even if the analyst forgets to sample.
///
/// (duckdb-rs 1.10503.1 exposes no aggregate-UDF registration API, so this
/// ships as a scalar over LIST rather than a true aggregate — see choice 0064.)
struct FineTypeProfile;

impl VScalar for FineTypeProfile {
    type State = ();

    unsafe fn invoke(
        _state: &Self::State,
        input: &mut DataChunkHandle,
        output: &mut dyn WritableVector,
    ) -> Result<(), Box<dyn Error>> {
        let col_classifier = get_column_classifier();
        let len = input.len();
        let n_cols = input.num_columns();

        let struct_vec = output.struct_vector();
        let mut type_child = struct_vec.child(0, len);
        let mut conf_child = struct_vec.child(1, len);
        let mut ddb_child = struct_vec.child(2, len);

        for i in 0..len {
            let values = column_fn::read_list_varchar_capped(
                input,
                0,
                i,
                column_fn::PROFILE_SAMPLE_CAP,
            );

            let result = match values {
                None => {
                    // NULL list → NULL struct fields.
                    type_child.set_null(i);
                    conf_child.set_null(i);
                    ddb_child.set_null(i);
                    continue;
                }
                Some(vals) if vals.is_empty() => {
                    type_child.insert(i, "unknown");
                    conf_child.as_mut_slice::<f64>()[i] = 0.0;
                    ddb_child.insert(i, "VARCHAR");
                    continue;
                }
                Some(vals) => {
                    let header = if n_cols >= 2 {
                        read_varchar(input, 1, i).filter(|h| !h.is_empty())
                    } else {
                        None
                    };
                    match header {
                        Some(h) => col_classifier.classify_column_with_header(&vals, &h),
                        None => col_classifier.classify_column(&vals),
                    }
                }
            };

            match result {
                Ok(col_result) => {
                    let ddb = type_mapping::to_duckdb_type(&col_result.label);
                    type_child.insert(i, col_result.label.as_str());
                    conf_child.as_mut_slice::<f64>()[i] = col_result.confidence as f64;
                    ddb_child.insert(i, ddb);
                }
                Err(_) => {
                    type_child.insert(i, "unknown");
                    conf_child.as_mut_slice::<f64>()[i] = 0.0;
                    ddb_child.insert(i, "VARCHAR");
                }
            }
        }

        Ok(())
    }

    fn signatures() -> Vec<ScalarFunctionSignature> {
        let varchar = || LogicalTypeHandle::from(LogicalTypeId::Varchar);
        let ret = || {
            LogicalTypeHandle::struct_type(&[
                ("type", varchar()),
                ("confidence", LogicalTypeHandle::from(LogicalTypeId::Double)),
                ("duckdb_type", varchar()),
            ])
        };
        vec![
            ScalarFunctionSignature::exact(vec![LogicalTypeHandle::list(&varchar())], ret()),
            ScalarFunctionSignature::exact(
                vec![LogicalTypeHandle::list(&varchar()), varchar()],
                ret(),
            ),
        ]
    }
}

/// `ft_validate_text(value VARCHAR, schema VARCHAR) → STRUCT{valid, constraint, message}`
///
/// Validates a value (or a whole column, one row at a time) against a JSON
/// Schema fragment. Unlike `finetype_validate`, which returns a bare
/// `'valid'`/error string, this returns a STRUCT mirroring the CLI
/// `reject_errors` shape so a report can name which constraint failed:
///   - `valid` BOOLEAN
///   - `constraint` VARCHAR — `pattern` | `min_length` | … | `other` (NULL when valid)
///   - `message` VARCHAR — the `jsonschema` error text (NULL when valid)
///
/// Null semantics match `finetype validate`: an empty / `"null"` value is
/// skipped (valid), and a NULL / empty / non-object schema means the column
/// carries no constraint (valid). This is the per-cell engine the `ft_validate`
/// table macro calls under the hood.
struct FineTypeValidateText;

impl VScalar for FineTypeValidateText {
    type State = ();

    unsafe fn invoke(
        _state: &Self::State,
        input: &mut DataChunkHandle,
        output: &mut dyn WritableVector,
    ) -> Result<(), Box<dyn Error>> {
        let len = input.len();

        let struct_vec = output.struct_vector();
        let mut valid_child = struct_vec.child(0, len);
        let mut constraint_child = struct_vec.child(1, len);
        let mut message_child = struct_vec.child(2, len);

        for i in 0..len {
            let value = read_varchar(input, 0, i);
            let schema = read_varchar(input, 1, i);
            let (valid, constraint, message) =
                validate::validate_value_detail(value.as_deref(), schema.as_deref());

            valid_child.as_mut_slice::<bool>()[i] = valid;
            match constraint {
                Some(c) => constraint_child.insert(i, c.as_str()),
                None => constraint_child.set_null(i),
            }
            match message {
                Some(m) => message_child.insert(i, m.as_str()),
                None => message_child.set_null(i),
            }
        }

        Ok(())
    }

    fn signatures() -> Vec<ScalarFunctionSignature> {
        let varchar = || LogicalTypeHandle::from(LogicalTypeId::Varchar);
        let ret = LogicalTypeHandle::struct_type(&[
            ("valid", LogicalTypeHandle::from(LogicalTypeId::Boolean)),
            ("constraint", varchar()),
            ("message", varchar()),
        ]);
        vec![ScalarFunctionSignature::exact(
            vec![varchar(), varchar()],
            ret,
        )]
    }
}

/// `ft_validate(table, schema) → TABLE` — registered as a SQL table macro at
/// LOAD (not a Rust table function: the BindInfo catalog wall stands, choice
/// 0064). The macro expands into catalog-aware SQL that DuckDB executes with
/// full table access via `query_table(table)`.
///
/// It melts every column to VARCHAR with a name-free `COLUMNS(*)::VARCHAR`
/// UNPIVOT, joins each column to its `$.properties.<col>` subschema, and returns
/// a per-column report `{column_name, total, rejects, sample_message}`.
///
/// The one `schema` argument auto-detects its three forms: an inline JSON
/// literal (`trim(schema) LIKE '{%'`), a `getvariable()` reference (resolves to
/// inline JSON before the macro sees it), or a file path (read via `read_text`).
/// `CASE` short-circuits, so the inline branch never touches the filesystem.
///
/// Nested columns are guarded (Precision Principle): `typeof(COLUMNS(*))` flags
/// STRUCT / LIST / MAP / UNION / ARRAY columns, which are surfaced as an explicit
/// skip row ("unnest / to_json / extract before validating") instead of being
/// silently FALSE-rejected on their flattened display text.
const FT_VALIDATE_MACRO: &str = r#"CREATE OR REPLACE MACRO ft_validate(tbl, schema) AS TABLE
WITH
  resolved(s) AS (
    SELECT CASE WHEN trim(schema) LIKE '{%' THEN schema
                ELSE (SELECT content FROM read_text(schema)) END
  ),
  types AS (
    SELECT col AS column_name, ty AS column_type,
           (ty LIKE 'STRUCT%' OR ty LIKE 'MAP%' OR ty LIKE 'UNION%' OR ty LIKE '%]') AS nested
    FROM (SELECT typeof(COLUMNS(*)) FROM query_table(tbl) LIMIT 1)
    UNPIVOT (ty FOR col IN (COLUMNS(*)))
  ),
  melted AS (
    SELECT col AS column_name, val
    FROM (SELECT COLUMNS(*)::VARCHAR FROM query_table(tbl))
    UNPIVOT (val FOR col IN (COLUMNS(*)))
  ),
  scalar_report AS (
    SELECT m.column_name,
           count(*)::BIGINT AS total,
           count(*) FILTER (WHERE NOT ft_validate_text(m.val,
             json_extract((SELECT s FROM resolved), '$."properties"."' || m.column_name || '"')::VARCHAR).valid)::BIGINT AS rejects,
           any_value(ft_validate_text(m.val,
             json_extract((SELECT s FROM resolved), '$."properties"."' || m.column_name || '"')::VARCHAR).message)
             FILTER (WHERE NOT ft_validate_text(m.val,
             json_extract((SELECT s FROM resolved), '$."properties"."' || m.column_name || '"')::VARCHAR).valid) AS sample_message
    FROM melted m JOIN types tp USING (column_name)
    WHERE NOT tp.nested
    GROUP BY m.column_name
  ),
  nested_report AS (
    SELECT tp.column_name, NULL::BIGINT AS total, NULL::BIGINT AS rejects,
           'nested ' || tp.column_type || ' column — unnest / to_json / extract before validating' AS sample_message
    FROM types tp WHERE tp.nested
  )
  SELECT * FROM scalar_report
  UNION ALL
  SELECT * FROM nested_report
  ORDER BY column_name;
"#;

// ═══════════════════════════════════════════════════════════════════════════════
// EXTENSION ENTRYPOINT
// ═══════════════════════════════════════════════════════════════════════════════

/// # Safety
///
/// Called by DuckDB when loading the extension. The Connection is valid for the
/// lifetime of the extension.
///
/// `ext_name = "finetype"` bakes the entrypoint symbol (`finetype_init_c_api`) so
/// the artifact loads as `finetype.duckdb_extension` regardless of build env, and
/// `min_duckdb_version = "v1.2.0"` declares the stable C API floor (choice 0063) —
/// one artifact stays loadable on DuckDB 1.2 through 1.5+.
#[duckdb_entrypoint_c_api(ext_name = "finetype", min_duckdb_version = "v1.2.0")]
pub unsafe fn extension_entrypoint(con: duckdb::Connection) -> Result<(), Box<dyn Error>> {
    con.register_scalar_function::<FineTypeVersion>("finetype_version")
        .expect("Failed to register finetype_version");

    con.register_scalar_function::<FineTypeValidate>("finetype_validate")
        .expect("Failed to register finetype_validate");

    con.register_scalar_function::<FineType>("finetype")
        .expect("Failed to register finetype");

    con.register_scalar_function::<FineTypeDetail>("finetype_detail")
        .expect("Failed to register finetype_detail");

    con.register_scalar_function::<FineTypeCast>("finetype_cast")
        .expect("Failed to register finetype_cast");

    con.register_scalar_function::<FineTypeUnpack>("finetype_unpack")
        .expect("Failed to register finetype_unpack");

    // Spike (ac-04) — NOT a production function. Registers a trivial
    // table function to preserve the compile-time evidence that (a) vtab
    // is active under loadable-extension and (b) scalar + table function
    // coexistence compiles. No production use — the spike ratified
    // rollback_plan Scenario A (see MADR 0064); the CLI calls
    // finetype_core::table_validator::validate_table directly and writes
    // rejects to the output .db via duckdb-rs (spec ac-06 / ac-09).
    con.register_table_function::<spike::FineTypeSpike>("finetype_spike")
        .expect("Failed to register finetype_spike (spike artefact — not production)");

    // ── ft_ converged surface (spec 2026-06-03-duckdb-extension-table-verbs) ──
    // The un-prefixed scalars above stay registered as aliases for one release
    // so the v0.6.22 community install keeps working; new docs teach the ft_
    // names. ft_infer (single-value probe) and ft_profile (column, the accurate
    // path) are genuinely new; ft_validate_text returns a STRUCT; ft_cast /
    // ft_unpack / ft_version alias the existing scalar impls.
    con.register_scalar_function::<FineTypeVersion>("ft_version")
        .expect("Failed to register ft_version");
    con.register_scalar_function::<FineTypeInfer>("ft_infer")
        .expect("Failed to register ft_infer");
    con.register_scalar_function::<FineTypeProfile>("ft_profile")
        .expect("Failed to register ft_profile");
    con.register_scalar_function::<FineTypeValidateText>("ft_validate_text")
        .expect("Failed to register ft_validate_text");
    con.register_scalar_function::<FineTypeCast>("ft_cast")
        .expect("Failed to register ft_cast");
    con.register_scalar_function::<FineTypeUnpack>("ft_unpack")
        .expect("Failed to register ft_unpack");

    // ft_validate(table, schema) ships as a SQL table macro, not a Rust table
    // function: the macro expands into catalog-aware SQL DuckDB runs with full
    // table access (query_table), reaching past the BindInfo catalog wall that
    // blocks Rust table functions on this pin (choice 0064).
    con.execute_batch(FT_VALIDATE_MACRO)
        .expect("Failed to register ft_validate table macro");

    Ok(())
}
